### ISSUE TITLE
Allow arbitrary redirect_uri

### ISSUE THREAD

**Issue by xmedeko** [lepture/authlib#106]
I would like to have a possibility that client may pass any redirect URI, not just URIs specified in DB. Desktop applications usually need to pass `http://localhost:xyz` where the xyz is the first free random port. E.g. if no `redirect_uri` is specified in DB, then allow all, see class `OAuth2ClientMixin`:
```py
   def check_redirect_uri(self, redirect_uri):
        return not self.redirect_uris or redirect_uri in self.redirect_uris 
```
(and the doc in the parent class `ClientMixin.check_redirect_uri`).

I know I may override the default behaviour, but I think this behaviour should be by default. (Now, if no `redirect_uri` is specified, then all clients are blocked.)

**Comment by lepture** [comment]
The default behavior should be secure enough for programmers. If you wishi to allow any url, you can overwrite the method.

**Comment by xmedeko** [comment]
Yes, I've already overwritten the method. The SQL model is `oauth_client.redirect_uri IS NOT NULL`, so I have to override the default data model as well, or choose some value (like empty string) which mean _any uri_. 

Furthermore, the current example [example-oauth2-server](https://github.com/authlib/example-oauth2-server) is confusing. It allows to submit a new client without entering any data to the `redirect_uri` text box, which makes the client unusable. (Similarly to other fields.)

I suggest to make `oauth_client.redirect_uri` nullable and change GUI of the example [example-oauth2-server](https://github.com/authlib/example-oauth2-server) like Facebook (and other sites) have: 
- Do not allow so submit empty `redirect_uri` by default.
- Make a checkbox like "Allow any redirect URI (not recommended)". When switched on, the `redirect_uri`  box will be disabled and empty.

If you want to keep the current functionality, I think some doc (maybe in the [example-oauth2-server](https://github.com/authlib/example-oauth2-server) to prevent the initial confusion.

Thanks
