### ISSUE TITLE
Support encryption and/or hashing of client_secret

### ISSUE THREAD

**Issue by SaintSimmo** [lepture/authlib#107]
Should the `client_secret` issued to a new confidential `Client` be encrypted in the database? Considering a `client_secret` is akin to a password it stands to reason it should be encrypted at rest (or hashed with the secret being presented only a single time at Client creation). Currently the builtin OAuth2ClientMixin will store the `client_secret` in plaintext. 

I haven't been able to find anything related to this issue even in passing so I'm curious why it's seemingly not a consideration.

**Comment by lepture** [comment]
No, client secret is not a password. It is generated by your program, not inputted by human.

However, you can subclass Client to do whatever you want.

**Comment by SaintSimmo** [comment]
> No, client secret is not a password. 

Sorry, just to be clear it is _akin_ (equivalent or similar) to a password in that it is extremely sensitive and can be used to gain access to resources. It should absolutely be stored in the provider DB either encrypted or (ideally) hashed.

**Comment by NicolasLM** [comment]
The same issue exists regarding access and refresh tokens. They also behave similarly to passwords: the server only needs a hash of them to work properly.

There is even a [section of RFC 6819](https://tools.ietf.org/html/rfc6819#section-4.3.2) that discusses the problem:

> 
> Threat: Obtaining Access Tokens from Authorization Server Database
> 
> This threat is applicable if the authorization server stores access tokens as handles in a database.  An attacker may obtain access tokens from the authorization server's database by gaining access to the database or launching a SQL injection attack.
> 
> Impact: Disclosure of all access tokens.
> 
> Countermeasures:
> - Store access token hashes only

In my opinion the example repository should err on the side of security and hash these fields.
