### ISSUE TITLE
Documentation for Flask, OAuth and Database Setup is unclear

### ISSUE THREAD

**Issue by proegssilb** [lepture/authlib#108]
On the documentation page for the [flask client](https://docs.authlib.org/en/latest/client/flask.html), in the "Database" section, the following comments are made:

> If OAuth login is what you need ONLY, you don’t need to configure a database with fetch_token method.

> To send requests on behalf of the user, you need to save user’s access token into database after authorize_access_token. Then use the access token with fetch_token from database.

(Note: Those two quotes are rather far apart, so if you're skimming and find one, it's easy to miss the other)

There are a few questions the database code in that section does not answer, though. Flask itself does not define an ORM (which appears to be what you're using for the code example), so I don't know which ORM you're using, nor how you set it up to work with Flask and authlib. I also don't know which particular methods are talked about for "sending requests", although I can infer you mean `.get(...)` and `.post(...)` based on text elsewhere on the page. Lastly, that section leaves the references to `fetch_token` undefined.

Let me provide a couple ideas of how to improve the issue. Feel free to do something different.

The code clarity issue could be resolved by linking to the library used (and a tutorial of how to integrate it with Flask), and showing some more code of how the database is integrated with authlib in the "Database" section's code example.

Additionally, I think the description of when I need to setup a database could be made more clear. Moving the two quotes I found closer together would help, but so would focusing on positive phrasing (for example, "You need to setup a database when you call functions that access the service's API outside of login, such as `.get` and `.post`.").

Lastly, converting the references to `fetch_token` to a hyperlink to an API reference page (if one exists) or a section of the document with more information would help make sure everyone knows exactly what is being referenced.

Those are just my ideas. Maybe there's a different approach that would work more effectively.

**Comment by SaintSimmo** [comment]
This has been my experience the past few weeks of working with this lib from a Authorization Server perspective as well. There is _a lot_ missing from the official docs - at least with regards to Flask - so it's required a lot of reading the RFC to piece things together (which has been helpful in its own right). This is especially true when it comes to setting and getting attributes on the sqla mixins. 

Also something that has been of help is reading through their implementation examples in [authlib/playground](https://github.com/authlib/playground), though that's been offline for a while now, and from reading their Flask tests in this project.

**Comment by lepture** [comment]
document updated
