### ISSUE TITLE
`OAuth2Session.add_token()` does not exist

### ISSUE THREAD

**Issue by nfvs** [lepture/authlib#11]
```
  File "/Users/nsantos/.virtualenvs/oauth/lib/python3.6/site-packages/authlib/client/oauth2.py", line 293, in request
    url, headers, data, self.token_placement
TypeError: 'NoneType' object is not callable
```

This is the snippet that triggers that (in `request()`):
```
            url, headers, data = self.add_token(
                self.token['access_token'],
                url, headers, data, self.token_placement
            )
```

`OAuth2Session.add_token` does not exist (it's `None`).

**Comment by nfvs** [comment]
Sorry it actually exists as a property, but it was returning `None`:
```python
    @property
    def add_token(self):
        if not self.token:
            return None

        token_type = self.token['token_type'].lower()
        if token_type == 'bearer':
            return add_bearer_token
```

I followed the docs and had `token_type="oauth1.0"`, which was making that function return `None`.

**Comment by lepture** [comment]
@nfvs OAuth2Session is designed for OAuth 2. Currently, it only supports `bearer` token.

> I followed the docs and had `token_type="oauth1.0"`

Where did you find this in the documentation? It must be a mistake.

Are you trying OAuth 1? Then you should use `OAuth1Session`.

**Comment by nfvs** [comment]
I'm using OAuth 2 actually. My mistake, the model only has `OAUTH1_TOKEN_TYPE = 'oauth1.0'`: https://docs.authlib.org/en/latest/client/frameworks.html#cache-database

I'm storing the tokens in flask's session cookie, right after calling `authorize_access_token()`, and then in `fetch_token` I was just hardcoding a `token_type`.

**Comment by lepture** [comment]
@nfvs It is not safe to store a token in session cookies. If you are just doing it for testing, that's ok.
