### ISSUE TITLE
add support for custom json serializer

### ISSUE THREAD

**Issue by unitto1** [lepture/authlib#110]
Hey! When I checked the official site of JWT I found 4 different libs for python. Your lib is most interesting in my opinion. But I was very surprised when I wasn't found the opportunity to pass ujson for CPython or SimpleJson for Pypy as a used serializer. Also, I checked the corresponding module and I can add support for this by try \ except in imports or via passing serializer object to the init method. Does it interesting for somebody?

**Comment by lepture** [comment]
It would be good to have such a thing. But I would like to add it after v1.0
