### ISSUE TITLE
documentation describes version that's not release yet

### ISSUE THREAD

**Issue by alantw** [lepture/authlib#116]
[Current documentation](https://docs.authlib.org/en/latest/index.html) points to the lastest code which hasn't been released yet. The latest version released is 0.10, which can also be found on [Pypi](https://pypi.org/project/Authlib/). I feel like pointing the correct documentation to the corresponding release would definitely be less confusing.

**Comment by lepture** [comment]
You can find the "stable" version on sidebar.

**Comment by alantw** [comment]
Ahh sorry didn't see that! Thanks!
