### ISSUE TITLE
OpenIDHybridGrant never call create_token_response() if OpenIDCodeGrant registered first and vice versa

### ISSUE THREAD

**Issue by namlh-teko** [lepture/authlib#118]
As we implement OpenID Connect for Flask as in [tutorial](https://docs.authlib.org/en/latest/flask/2/openid-connect.html), we realize that `parse_authorization_code()`, `delete_authorization_code()` and `authenticate_user()` in `OpenIDHybridGrant` class are never called.

The problem is [`check_token_endpoint()`](https://github.com/lepture/authlib/blob/master/authlib/oauth2/rfc6749/grants/base.py#L44) in [`BaseGrant`](https://github.com/lepture/authlib/blob/master/authlib/oauth2/rfc6749/grants/base.py) return `True` with both `OpenIDCodeGrant` and `OpenIDHybridGrant`. So whichever grant is registered first, get calls `create_token_response()`.

Should we need to change the implementation of `check_token_endpoint()`?

**Comment by lepture** [comment]
@namlh-teko It is correct. Because they share the same logic. Both `OpenIDCodeGrant` and `OpenIDHybridGrant` are subclass of `AuthorizationCodeGrant`. The `create_token_response` will use the `authorization_code` to create access token.

**Comment by namlh-teko** [comment]
@lepture Thanks for your quick reply.
But I mean, does it kind of confuse, when the flow uses `OpenIDHybridGrant` to receive `code`, but `OpenIDCodeGrant` to exchange `code` for `token`?

**Comment by lepture** [comment]
@namlh-teko I need to update the documentation. OpenID is an extension for Authorization Code Grant now.

**Comment by lepture** [comment]
I have updated the logic for "Grant". There won't be this problem in v0.12.

https://github.com/lepture/authlib/commit/cf524898723f8b4b03b6417942d7f6bf89a9e7ad
