### ISSUE TITLE
Non-Compliant Responses from RFC 7009 Token Revocation

### ISSUE THREAD

**Issue by night** [lepture/authlib#119]
Per the RFC, invalid tokens should return a 200, but `invalid_request` is raised, which makes it a 400 response status.

https://github.com/lepture/authlib/blob/master/authlib/oauth2/rfc7009/revocation.py#L41

> The authorization server responds with HTTP status code 200 if the
> token has been revoked successfully or if the client submitted an
> invalid token.
>
> Note: invalid tokens do not cause an error response since the client
> cannot handle such an error in a reasonable way.  Moreover, the
> purpose of the revocation request, invalidating the particular token,
> is already achieved.

More details at https://tools.ietf.org/html/rfc7009#section-2.2

**Comment by lepture** [comment]
Thanks. I've fixed in https://github.com/lepture/authlib/commit/90aff451787fd95fbca0d5d7e167c21af430b301
