### ISSUE TITLE
validate_xyz() in JWTClaims should use UTC?

### ISSUE THREAD

**Issue by blackmagic02881** [lepture/authlib#123]
the time in validate() should be UTC? 

https://github.com/lepture/authlib/blob/master/authlib/jose/rfc7519/claims.py#L59

**Comment by bjmc** [comment]
[time.time() returns the UNIX epoch](https://docs.python.org/3/library/time.html#time.time), not a datetime object. It doesn't have a timezone (UTC or otherwise) associated.

**Comment by blackmagic02881** [comment]
that is why it need to use something like  int(time.mktime(datetime.utcnow().timetuple())) instead of time.time()

from RFC7519, all time need to be in UTC. 

 NumericDate
      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.

**Comment by lepture** [comment]
> A JSON numeric value representing the number of seconds from
1970-01-01T00:00:00Z UTC until the specified UTC date/time,
ignoring leap seconds.

It is called epoch. And `time.time()` returns epoch.
