### ISSUE TITLE
Async Client with OAuth2 and JWT Client Assertions

### ISSUE THREAD

**Issue by mfulgo** [lepture/authlib#129]
This is somewhat related to #63, but it seemed like it could be tracked separately.

I'm attempting to use Authlib for a JWT Bearer grant while also using `aiohttp`.
1. I wasn't able to find any documentation on using the _AsyncOAuth2Client for aiohttp_, similar to the documentation for the [AsyncOAuth1Client for aiohttp](/lepture/authlib/blob/master/docs/client/oauth1.rst#asyncoauth1client-for-aiohttp).
2. I'm still hacking and debugging, but there seems to be some issue(s) using the AsyncOAuth2Client in conjunction with a JWT Client Assertion. Then again, this could just be because I've configured it incorrectly. I'm attempting to adapt the information from [here](https://docs.authlib.org/en/latest/specs/rfc7523.html#jwt-oauth2session) to the async client.

For point 2, the issue I'm currently running into is that the `data` kwarg passed into `authlib.client.aiohttp.OAuthRequest` is a `dict` rather than a percent-encoded query string: It eventually ends up as the `body` parameter in `authlib/oauth2/rfc7523/auth.py` and is passed to `add_params_to_qs`, which raises an error (because it's expecting a query string). Again... this could just be because I don't have it set up correctly yet.

I also see a potential issue that I haven't quite gotten to yet: I need to set a `sub` in the JWT that is different from the `iss`. However, it looks like the `_sign` method sets both values to `client_id`.

Thanks

**Comment by lepture** [comment]
aiohttp is currently an experimental feature. I haven't added AsyncAssertSession yet.

**Comment by lepture** [comment]
This is added https://docs.authlib.org/en/latest/client/aiohttp.html#asyncassertionclient-for-aiohttp

Not released yet. You can try the master code.

**Comment by Dreamsorcerer** [comment]
I can't find aiohttp anywhere in the documentation, either as a client or as a server (as mentioned in #340).

I can only find this commit referencing an authlib-aiohttp, which doesn't actually exist...
https://github.com/authlib/authlib/commit/d4925a9c1526f1429ee71145362c317fcfcabcf0

**Comment by Dreamsorcerer** [comment]
There appears to be this abandoned repo too: https://github.com/authlib/aiohttp-oauth-client
With an unhelpful about message telling users to use httpx instead..
