### ISSUE TITLE
OpenID connect documentation improvments

### ISSUE THREAD

**Issue by leogout** [lepture/authlib#133]
Maybe the docs on OpenID connect should mention `OIDCAuthorizationCodeMixin` and all the `UserInfo` + `generate_user_info` stuff. I had to tryhard with my debugger to find out about both of these. Can I make a PR to tell people about it ?
Thanks for this library by the way, it is full of good surprises and I love it.

**Comment by lepture** [comment]
@leogout Thanks. I'd like to receive documentation improvements.
