### ISSUE TITLE
Redirect_uri is used before it is checked

### ISSUE THREAD

**Issue by cziebuhr** [lepture/authlib#142]
In `validate_code_authorization_request`, `redirect_uri` is used for `InvalidClientError` before it has been checked with `validate_authorization_redirect_uri`. This allows an attacker to redirect to any given uri.

I did not yet consider it security relevant, as it's only in master and not released yet.

**Comment by cziebuhr** [comment]
After having a look again into RFC-6749, I've also seen that `invalid_client` is not listed as valid error response for authorization endpoint (only for token endpoint). But I'm also not sure which error code to use instead.

**Comment by lepture** [comment]
Thanks, fixed. `InvalidClientError` should not contain redirect_uri
