### ISSUE TITLE
Flask OAuth Client: refreshed token is not used

### ISSUE THREAD

**Issue by yclybouw** [lepture/authlib#144]
Using version 0.11

File: authlib/flask/client/oauth.py
Class: RemoteApp

1. The first time a "authenticated" request is made, the `RemoteApp.token` property will fetch the token with `RemoteApp._fetch_token` and put it on Flask's `_app_ctx_stack`.
1. Each subsequent request will not use `RemoteApp._fetch_token`, but the cached token from `_app_ctx_stack`.
1. If the token has expired, a new token will be requested (authlib/oauth2/client.py:OAuth2Client), it is updated in this session object, but this not propagate to RemoteApp, nor `_app_ctx_stack`.
1. Next request, RemoteApp.token will still return the old token from `_app_ctx_stack`.

**Comment by lepture** [comment]
fixed by 4d570fa25cb1b6d892bc369ea3e657196cfcaaca
