### ISSUE TITLE
RFE: integration with FastAPI/Starlette

### ISSUE THREAD

**Issue by jonathanunderwood** [lepture/authlib#148]
[FastAPI ](https://github.com/tiangolo/fastapi)is rapidly gaining popularity as an API framework. It would be great if there was an integration client for FastAPI like there is for Flask etc.

FastAPI doesn't have a plugin system like Flask, but Starlette supports middlewares, and FastAPI supports dependency injection, so I think it should be possible.

**Comment by lepture** [comment]
See #64

**Comment by lepture** [comment]
See #63

**Comment by jonathanunderwood** [comment]
Slightly surprised to see this closed with a reference to #63 - FastAPI bindings donn't require async capability in Authlib (although, if Authlib were async compatible, FastAPI could take advantage of that).

Since you closed this, I assume you're not interested in adding this feature. In which case I'll look into adding them, and submit them as a PR.

Just looking at the code for the Flask bindings, and I have a question: I see the state is stored client side in the session. Is there any reason for doing this rather than storing state server side?

**Comment by lepture** [comment]
@jonathanunderwood Oh, I see. You just need the "client" part, not the server part.

I'm creating a httpx implementation right now. I'll add FastAPI integration in the httpx binding since it supports both sync and async mode.

**Comment by jonathanunderwood** [comment]
Yeah, my use case is for a client binding only, similar to the flask and django ones.

**Comment by jonathanunderwood** [comment]
OK, I have something working for this, not yet PR ready, but I have a question: The flask client has `update_token` support, but the django client doesn't - why is that? I am trying to work out if that's needed for the FastAPI client.

**Comment by lepture** [comment]
@jonathanunderwood Django is using signal to handle token update. Need to add that in documentation.

**Comment by jonathanunderwood** [comment]
Closing this one, since #153 has been merged.
