### ISSUE TITLE
OIDC compliance for flask server: POST to /authorize does not use form data

### ISSUE THREAD

**Issue by rudyardrichter** [lepture/authlib#15]
The README lists OpenID Connect as an implemented feature, so I assume this implementation is meant to be fully OIDC compliant. However, the default flask implementation doesn't get the request parameters from the form data, as described by OIDC spec:
```
If using the HTTP POST method, the request parameters are serialized using Form Serialization, per Section 13.2.
```

Here is my understanding what happens currently for the flask server handling a POST to /authorize:

- [`create_authorization_response`](https://github.com/lepture/authlib/blob/master/authlib/flask/oauth2/authorization_server.py#L123-L141) is called from the endpoint
- [`create_valid_authorization_response`](https://github.com/lepture/authlib/blob/master/authlib/specs/rfc6749/authorization_server.py#L83-L102) is called from above
- [`get_authorizaton_grant`](https://github.com/lepture/authlib/blob/master/authlib/specs/rfc6749/authorization_server.py#L38-L53) is called from above
- [`get_authorization_grant` attempts to parse params from query string (not form data)](https://github.com/lepture/authlib/blob/master/authlib/specs/rfc6749/authorization_server.py#L45)

It seems like it would be straightforward to check `flask.request.method` and grab the params from `flask.request.form` if the method is POST. I'd be happy to submit a PR for this if that would be welcomed.

**Comment by lepture** [comment]
@rudyardrichter I'm sorry for the misunderstanding. Currently only the OIDC client part is implemented, the server part is not yet. The next version is focusing on OAuth 1 server, so that it will take some time for OIDC server ready to use.

> get_authorization_grant attempts to parse params from query string (not form data)

No, it should parse params from query string. This authorization_grant is used for the "dialog page that user (with or without login form) is asked to grant the access (or not)". This very page is landed by a redirection from your application to the OAuth server, it can't be a POST request.

**Comment by rudyardrichter** [comment]
@lepture Supporting POST to the authorization endpoint is [optional according to RFC 6749](https://tools.ietf.org/html/rfc6749#section-3.1):
```
The authorization server MUST support the use of the HTTP "GET"
method [RFC2616] for the authorization endpoint and MAY support the
use of the "POST" method as well.
```
and [mandatory in OIDC](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest):
```
Authorization Servers MUST support the use of the HTTP GET and POST
methods defined in RFC 2616 [RFC2616] at the Authorization Endpoint.
Clients MAY use the HTTP GET or POST methods to send the Authorization
Request to the Authorization Server.
```
where, as I quoted above, OIDC stipulates that parameters for POST be in form data.

I suppose this is slightly moot until OIDC provider is supported. Still, even for OAuth, it would be nice to allow support use of POST for the authorization endpoint.

**Comment by lepture** [comment]
@rudyardrichter yes, you are right. I'll make a change in v0.4.

**Comment by lepture** [comment]
It's collecting form data now. close it.
