### ISSUE TITLE
Support multiple audiences for OpenIDCode

### ISSUE THREAD

**Issue by cal97g** [lepture/authlib#150]
It should be possible to provide multiple audiences to JWT Tokens via OpenIDCode child classes.

`authlib.oidc.core.grants.code.OpenIDCode` & `authlib.oidc.core.grants.implicit.OpenIDImplicitGrant` both use `generate_id_token` from `authlib.oidc.core.grants.util` to generate id_token payloads.

`generate_id_token` defines the audience to be `[client.get_client_id()]`

We should add a parameter to allow a token to support multiple audiences.

**Comment by cal97g** [comment]
fwiw this is my patch to the function which adds support for multiple audiences:
```
def my_generate_id_token(
    token, request, user_info, key, alg, iss, exp, nonce=None, auth_time=None, code=None
):
    client = request.client

    url_params = urllib.parse.parse_qs(request.uri)

    try:
        audience = []
        for aud in url_params["audience"]:
            audience.append(aud)
        audiences = list(set(audience))
    except KeyError as e:
        audiences = [client.get_client_id()]

    payload = authlib.oidc.core.grants.util._generate_id_token_payload(
        alg=alg,
        iss=iss,
        aud=audiences,
        exp=exp,
        nonce=nonce,
        auth_time=auth_time,
        code=code,
        access_token=token.get("access_token"),
    )
    payload.update(user_info)
    return authlib.oidc.core.grants.util._jwt_encode(alg, payload, key)
```

**Comment by lepture** [comment]
Developers can rewrite `get_audiences` method now.

**Comment by cal97g** [comment]
@lepture great! Thanks for this.
