### ISSUE TITLE
Django OAuth2 Client: multiple values for keyword argument 'refresh_token_url'

### ISSUE THREAD

**Issue by KaczuH** [lepture/authlib#151]
Version: 0.11

**How to reproduce**

```python
from authlib.django.client import OAuth
oauth = OAuth()

client = oauth.register(
    name="client_name",
    client_id="{{ client_id }}",
    client_secret="{{ client_secret }}",
    access_token_url="{{ access_token }}",
    authorize_url="{{ authorize_url }}",
    api_base_url="{{ api_base_url }}",
    client_kwargs={
        'refresh_token_url': "{{ refresh_token_url }}"
    }
)

client.get("{{ some_endpoint }}")
```
Results in an exception
`TypeError: multiple values for keyword argument 'refresh_token_url'`

~Probably the same issue occurs in Flask client~
It is fixed on `master` for Flask

`refresh_token_url` is required to set up the `token_update` signal.

I think i know how to fix it
I have created a PR #152

**Comment by lepture** [comment]
Fixed by #152
