### ISSUE TITLE
create_oauth_request should support JSON payloads out of the box

### ISSUE THREAD

**Issue by mmattax** [lepture/authlib#156]
**Is your feature request related to a problem? Please describe.**

The flask and Django helpers both take `use_json` in `create_oauth_request`, but this flag is never used in the integration code itself, causing developers to have to build the request object manually if the endpoint accepts JSON. 

I'm porting over existing code that used Flask-OAuth2lib which seemed to do this.

**Describe the solution you'd like**

The helper code should look at the headers and determine if it should use JSON automatically.

```python
use_json = request.headers.get('Content-Type').find('application/json') != -1
```

**Describe alternatives you've considered**

I've currently built my own helper that looks at the content type:

```python
def create_oauth_request(request):
    """
    Ported function from flask_helpers.py (link below) to improve JSON support.
    https://github.com/lepture/authlib/blob/master/authlib/integrations/flask_helpers.py
    """
    from authlib.oauth2 import OAuth2Request
    from authlib.common.encoding import to_unicode
    body = None
    if request.method == 'POST':
        if request.headers.get('Content-Type').find('application/json') != -1:
            body = dict(request.json)
        else:
            body = request.form.to_dict(flat=True)
        
    url = request.base_url
    if request.query_string:
        url = url + '?' + to_unicode(request.query_string)

    return OAuth2Request(request.method, url, body, request.headers)
```

I'm happy to submit a PR with this built-in if it gets your support.

**Comment by lepture** [comment]
@mmattax Hi, this `use_json` is used in:

```py
    def create_json_request(self, request):
        return create_oauth_request(request, HttpRequest, True)
```

**Comment by YPCrumble** [comment]
@lepture I'm facing the same issue as @mmattax was here. I'm trying to allow JSON requests to my OAuth server and currently only urlencoded form requests are possible. Would it make sense to dynamically call `create_oauth2_request` or `create_json_request` based on the request headers? Currently I can't see how `create_json_request` would ever be callable during the authentication flow - it only seems to be called for protected calls with an OAuth Access token already in place. 

Happy to submit a PR if you'd consider it!

**Comment by lepture** [comment]
@YPCrumble Authlib respects standard. As RFC6749 stated, the payload should be in `application/x-www-form-urlencoded`, you can't send JSON payload to token endpoint. In this case, I will not accept such a PR.

You can always rewrite the `create_oauth2_request` method on your `AuthorizationServer` so that your provider can accept JSON payload. But Authlib won't provide it by default.
