### ISSUE TITLE
0.12.1 ImportError: No module named 'authlib.integrations'

### ISSUE THREAD

**Issue by aradnaev** [lepture/authlib#157]
**Describe the bug**
Cannot import OAuth following examples in https://docs.authlib.org/en/latest/client/oauth2.html
using these import statements.
`from authlib.integrations.requests_client import OAuth2Session`
 `from authlib.integrations.django_client import OAuth`

ImportError: No module named 'authlib.integrations'

Upon examination, indeed there is no integrations directory in installed package.

Workaround:
If installing straight from github version 0.13.dev0, there is no problem
in requirements.txt:
git+git://github.com/lepture/authlib.git@master

**Error Stacks**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'authlib.integrations'


```

**To Reproduce**

1. create and activate new virtual environment  (e.g. `conda create -n authlib_test  python=3.5`, `conda activate authlib_test`
)
2. install authlib with pip `pip install Authlib`
and verify installation success (Successfully installed Authlib-0.12.1 cffi-1.13.0 cryptography-2.8 pycparser-2.19 six-1.12.0)
3. try importing OAuth following examples https://docs.authlib.org/en/latest/client/oauth2.html
`from authlib.integrations.requests_client import OAuth2Session`
 `from authlib.integrations.django_client import OAuth`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'authlib.integrations'

**Expected behavior**

should be no Import error and OAuth module available

**Environment:**

 - OS: MacOS 10.14.6
 - Python Version: 3.5.6
 - Authlib Version: 0.12.1

**Additional context**

NA

**Comment by lepture** [comment]
![image](https://user-images.githubusercontent.com/290496/67156092-d8179900-f34c-11e9-812a-35eb52016579.png)

**Comment by lepture** [comment]
https://docs.authlib.org/en/stable/client/oauth2.html

**Comment by aradnaev** [comment]
ah yes, thanks for clarifying. I should have paid closer attention to docs version, sorry for the distraction.

**Comment by iamshreeram** [comment]
@aradnaev , @lepture - I'm seeing similar issue. I was following this [doc](https://docs.authlib.org/en/stable/client/flask.html).

Though I have Authlib installed, I'm seeing below error -

```
from authlib.integrations.flask_client import OAuth
ModuleNotFoundError: No module named 'authlib'
```
