### ISSUE TITLE
Support for parameters in URI when getting access token

### ISSUE THREAD

**Issue by hillstub** [lepture/authlib#158]
Love the library - it's really useful!!

There's one thing that's causing me some problems, though. I'm trying to make this library work with the bunq OAuth2 authorization process (see [https://doc.bunq.com/#/oauth](https://doc.bunq.com/#/oauth)). The problem with their implementation is that they require a POST request with ```grant_type```, ```code```, ```redirect_uri```, ```client_id```, and ```client_secret``` as GET variables (so encoded in the URL). So far, I don't see a proper way to achieve this with the authlib library. (If I understand it correctly ```register_compliance_hook``` cannot be used to form a request for an access token.)

I got it working by changing the code in ```authlib/oauth2/client.py``` for the function ```_fetch_token``` and added the following

```
        if method.upper() == 'POST':
            resp = self.session.post(
                url+"?"+body, headers=headers,
                auth=auth, **kwargs)
```
This is obviously pretty hacky. Does someone has a better solution?

**Comment by lepture** [comment]
@hillstub thanks for reporting this. Interesting, how can a provider claims that is OAuth? I'll add a `access_token_request` hook in v0.13.

**Comment by lepture** [comment]
I figured it out, what you need is defining a new auth method. Something like:

```python
def auth_client(client, method, uri, headers, body):
    uri = add_params_to_uri(uri, [('client_id', client.client_id), ('client_secret',  client.client_secret])
    uri = uri + '&' + body
    body = ''
    return uri, headers, body

session = OAuth2Session(..., token_endpoint_auth_method='client_secret_get', ...)
session.register_client_auth_method('client_secret_get', auth_client)
```

**Comment by hillstub** [comment]
Thank you @lepture! That's helpful!

I'm actually using this in the context of a Flask application, so I'm using the `oauth.register` function. How can one do what you suggested above in a Flask app? (a session is not started explicitly)

**Comment by lepture** [comment]
@hillstub It was not supported in Flask. I've added this feature in v0.13

http://docs.authlib.org/en/latest/client/frameworks.html#client-authentication-methods

**Comment by hillstub** [comment]
Thank you, lepture!

>
