### ISSUE TITLE
Documentation clarification on JWE implementation details for RFC 7516

### ISSUE THREAD

**Issue by josh-marshall-jax** [lepture/authlib#159]
With regard to  https://docs.authlib.org/en/latest/specs/rfc7516.html#authlib.jose.JsonWebEncryption.serialize_compact

and

https://tools.ietf.org/html/rfc7516#section-3.3

For the uninitiated (like me) on first reading, including a key, even if encrypted in the response text seems like trouble.  A quick note on why it is OK would be nice.

From what I have read, I am inferring that core parts of the header are handled with PKI, then the ciphertext is encrypted/decrypted using a symmetric cipher using the unencrypted key.

**Comment by josh-marshall-jax** [comment]
I can't seem to change this to use the documentation tag over the bug tag.

**Comment by lepture** [comment]
This shouldn't be explained by Authlib. Anyway, see

> Encrypt the CEK with the recipient's public key using the RSAES-OAEP algorithm to produce the JWE Encrypted Key.

It is safe due to the above explain.
