### ISSUE TITLE
Flask RemoteApp.authorize_access_token() includes state parameter in request

### ISSUE THREAD

**Issue by lyschoening** [lepture/authlib#16]
When following the typical authorization flow, the access token is requested from the authorization redirect URI. The RemoteApp implementation for Flask copies all request arguments of this callback and attaches them to the request for the authorization token. 

```
@app.route('/authorize')
def authorize():
    token = oauth.google.authorize_access_token()
    # ...
```
https://github.com/lepture/authlib/blob/e01aafde608ef7e7f6b79ef2f8f9a28da328b8e6/authlib/flask/client/oauth.py#L190

The request arguments to the callback include "state", which does not need to be submitted with the request for the access token. Due to this, the Google API will respond with an error: "Parameter not allowed for this message type: state".

**Comment by lepture** [comment]
@lyschoening Did you really get that error message? You can try it on https://play.authlib.org/ with google connects.

The `state` parameter is popped out in `_prepare_authorization_code_body`:

https://github.com/lepture/authlib/blob/e01aafde608ef7e7f6b79ef2f8f9a28da328b8e6/authlib/client/oauth2.py#L329

**Comment by lepture** [comment]
We can discuss the current "implementation for Flask copies all request arguments" which I think can be changed. However, the problem you mentioned does not exist. That `state` is not included in the request.

**Comment by lepture** [comment]
@lyschoening Did you try the Google connect on https://play.authlib.org/ ? Which works pretty well.

Besides, that `state` is recommended to be included in authorization request according to RFC:
https://tools.ietf.org/html/rfc6749#section-4.1.1

**Comment by lyschoening** [comment]
Is https://play.authlib.org/ a Flask app/sending the state parameter?

I'm authorizing through https://accounts.google.com/o/oauth2/token, not https://www.googleapis.com/oauth2/v4/token, which could explain why the behavior is different.

Google's documentation does not mention a state parameter
https://developers.google.com/identity/protocols/OAuth2WebServer#exchange-authorization-code and from reading around it seems this is known non-standard behavior in Google's API.

**Comment by lyschoening** [comment]
I should add that `state` isn't the only parameter being forwarded. Every parameter on the callback response is forwarded (`authuser`, `session_state`, `prompt` in this case).

**Comment by lepture** [comment]
@lyschoening Is there any reason that you have to use `https://accounts.google.com/o/oauth2/token` instead of `https://www.googleapis.com/oauth2/v4/token`

I'm ok to change the default behavior of `request.args.to_dict(flat=True)`. But `state` will always be included, I don't think `https://accounts.google.com/o/oauth2/token` has done OAuth 2 right.

**Comment by lepture** [comment]
@lyschoening I've cleaned up params in `authorize_access_token`.

Here is the endpoints that I found for Google: https://accounts.google.com/.well-known/openid-configuration
