### ISSUE TITLE
create_s256_code_challenge shouldn't accept invalid code verifiers

### ISSUE THREAD

**Issue by flokli** [lepture/authlib#165]
**Describe the bug**

RFC7636 describes the code challenge using the following ABNF:
```
code-challenge = 43*128unreserved
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
ALPHA = %x41-5A / %x61-7A
DIGIT = %x30-39
```

This translates to the following regex:
```
[a-zA-Z0-9\-\.\_\~]{43,128}
```

`authlib` currently doesn't check if code challenges match the regex (but it should), and even docs and tests use invalid challenges.

IMHO, `create_s256_code_challenge` should verify the `code_verifier` and raise an error if it doesn't match the regex - I don't assume it's a considerable performance penalty.

We might also want to provide a `create_code_verifier` convenience method, and use this consistently throughout docs and tests.

**Comment by lepture** [comment]
Thanks for your report. We need to check code_verifier for none method too, so I put the validation in `validate_code_verifier`.

**Comment by flokli** [comment]
Thanks!
