### ISSUE TITLE
Scope value must start with `openid` to use OpenID Connect

### ISSUE THREAD

**Issue by namlh-teko** [lepture/authlib#166]
**Describe the bug**

In OpenID Connect scenarios, if we call `/oauth/authorize` with scope which not start with `openid` (for example: `profile openid`), it will return BadRequest with message `invalid_scope: Missing "openid" scope`. 

It's clear from this code:
https://github.com/lepture/authlib/blob/master/authlib/oidc/core/grants/util.py#L17-L19

From [OpenID Connect Core document](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), it is not imply the position of `openid` in `scope`.

I'm just confused if it is your intention or not so I open an issue here. It's super easy to fix, though.

**Comment by lepture** [comment]
thanks for your report.
