### ISSUE TITLE
Support for prepared requests

### ISSUE THREAD

**Issue by galak75** [lepture/authlib#168]
**Is your feature request related to a problem? Please describe.**

I would like to fire [prepared requests](https://requests.kennethreitz.org/en/master/user/advanced/#prepared-requests) using an `OAuth2Session`, but I currently have to inject an access_token myself; here is an example using the openId connect password flow:

```python
requests = [requests.Request('GET', 'https://example.org/api/item', params={'id': i}) for i in range(10)]

with OAuth2Session(client_id='my-client-id', client_secret='my-client-secret', scope=['openid', 'email']) as session:
    session.fetch_token(url='https://example.org/token', username='my-user', password='my-pass')

    for req in requests:
        session.send(session.prepare_request(req))
```
Requests sent to the API fail with a 401 response status, unless I inject the `session.token_auth` into each request (even if the session itself is responsible for preparing and sending these requests)

**Describe the solution you'd like**

`OAuth2Session` could overrive `requests.Session.prepare_request` method, and inject access token. I experimented 2 different working solutions, but I do not know which one is preferable:

solution 1:
```python
class OAuth2Session(OAuth2Client, Session):

    # ...

    def prepare_request(self, request):
        # Solution 1 : set auth to request before preparing it
        if self.token and request.auth is None:
            request.auth = self.token_auth
        return super(OAuth2Session, self).prepare_request(request)
```

solution 2:
```python
class OAuth2Session(OAuth2Client, Session):

    # ...

    def prepare_request(self, request):
        prepared_request = super(OAuth2Session, self).prepare_request(request)
        # Solution 2 : prepare_auth on prepared_request when a token is there
        if self.token:
            prepared_request.prepare_auth(self.token_auth)
        return prepared_request
```

**Ready to contribute**

Let me know if this additional feature looks reasonable to you, I'll submit a PR

Thank you

**Comment by lepture** [comment]
Is there a conflict between this `prepare_request` and `withhold_token` in `request` method? Sometimes we don't want to add the token  auth.

**Comment by galak75** [comment]
It looks like `requests.Session.request` method is calling `Session.prepare_request` before sending the resulting prepared request.
So this `withhold_token` might be forgotten.

2 thoughts:

- As per `requests.Session.prepare_request` docstring:
  > Constructs a `PreparedRequest` for transmission and returns it. 
     The `PreparedRequest` has settings merged from the `Request` instance
     and those of the `Session`.

  This is designed so that you keep a client state (cookies, auth, etc...) and fire as many requests as you need using the same client state properties
- Why would you use and `OAuth2Session` object to fire a request without the auth token ? Why not use a `requests.Session` object in such case ? Maybe there are use cases I cannot see ?

**Comment by galak75** [comment]
Another design question I have about `OAuth2Session` class: when fetching or refreshing a token, should'nt this token be stored in `Session.auth` attribute ? Then the access token would always be used when firing a request using this `OAuth2Session` instance.

My understanding is that this is one of the `requests.Session` responsibility to store this `auth` attribute and inject it to requests fired from a `Session` instance.

But once again: You probably have good reasons to fire requests from the `OAuth2Session` object without adding the token auth. Could you please explain me which use cases ?

BTW : Congrats for this amazing module!

**Comment by lepture** [comment]
You can to that with `OAuth2Auth`.

The reason why there is a `OAuth2Session` is that OAuth is too complex, you can't use a simple requests auth to handle every case.

And Authlib has built-in requests and httpx support, they share the same interface.
