### ISSUE TITLE
0.13 throws away oidc nonce provided by the application

### ISSUE THREAD

**Issue by ThiefMaster** [lepture/authlib#180]
See this snippet here:

https://github.com/lepture/authlib/blob/3834a2a80876a87cdaab4240d77185179970c3ab/authlib/integrations/_client/base_app.py#L189-L193

This is called from `RemoteApp.create_authorization_url` which is called by `RemoteApp.authorize_redirect` which is called by my application (I'm not using the registry).

So if I pass my own nonce (which I'm storing in the session myself) it gets overwritten, so when I try to parse the id token later it fails of course. I fixed it in my app [like this](https://github.com/indico/flask-multipass/commit/a1b1c66b005cf7bd3004e95f233b61f5a48304e1#diff-93b271e053133ae8d825183d84694e5aR126-R127) but it feels extremely ugly.

So it would be nice if:

- no new nonce was generated if the caller already provided one
- there was an api to access the session data without popping it and without using internal apis (`_get_session_data`); using `retrieve_access_token_params` just to get the nonce would be pretty inappropriate since it does much more
- there was a proper OIDC client built-in in addition to the standard OAuth2 client ;)

**Comment by lepture** [comment]
Fixed in v0.14
