### ISSUE TITLE
OIDC refresh token

### ISSUE THREAD

**Issue by leogout** [lepture/authlib#182]
Hello, following [this question](https://stackoverflow.com/questions/59855736/authlib-openid-connect-refresh-token) on SO, I was wondering if there is already a way to get a JWT from a refresh token exchange. For now, even when I specify the scope to be openid, I only get an id_token once and it's on the creation of the token. The refresh token exchange leaves me with a "classical" token, and no id_token is joined. 
Regarding the OIDC specification ([this part](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse)) I would like to know if there is a way to get a new id_token on refresh.
I can look into implementing it if you would like.

**Comment by bjmc** [comment]
Are you using Authlib as a client, or are you building an OIDC server?

According to the spec,

> Upon successful validation of the Refresh Token, the response body is the Token Response of Section 3.1.3.3 except that **it might not contain an id_token.**

It sounds like this is an implementation detail that's left up to the decision of the Authorization Server. If you're acting as a client and the server chooses sends you a new `id_token` then you get one, but the spec allows it to omit the `id_token`

If you're building a server and you'd like to include an `id_token` in the response you send, you might be able to wrap the [`RefreshTokenGrant`](https://github.com/lepture/authlib/blob/d53d79db51187fd0511e55794580adf5ec768696/authlib/oauth2/rfc6749/grants/refresh_token.py#L22) the same way [the `AuthorizationCodeGrant` is wrapped here](https://github.com/lepture/authlib/blob/d53d79db51187fd0511e55794580adf5ec768696/authlib/oidc/core/grants/code.py#L140) Note that the `RefreshTokenGrant` calls the `process_token()` hook that `OpenIDCode` uses to add the `id_token`.

**Comment by leogout** [comment]
Thanks for your reply, I am putting together an Authorization Server. You're right, this part is definetly up to interpretation, but I was wondering if such a mechanism existed out of the box in Authlib.

I'll live it open to propose the feature to the author, feel free to close it anytime.

**Comment by leogout** [comment]
I've seen this new way of doing things with the OIDC code flow:
```python
server.register_grant(AuthorizationCodeGrant, [OpenIDCode(require_nonce=False)])
```

Would it be possible to do like this:
```python
server.register_grant(RefreshTokenGrant, [OpenIDCode(require_nonce=False)])
```

**Comment by lepture** [comment]
@leogout can you try with:

```
server.register_grant(RefreshTokenGrant, [OpenIDCode(require_nonce=False)])
```

It is already supported in this way.
