### ISSUE TITLE
Flask JWT validation decorator

### ISSUE THREAD

**Issue by ctaggart** [lepture/authlib#184]
**Is your feature request related to a problem? Please describe.**

We have several Flask API apps that need to be secured [similar to this](https://auth0.com/docs/quickstart/backend/python/01-authorization#create-the-jwt-validation-decorator). OAuth 2.0 [client credentials ](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#get-a-token) will be used, so just the authentication headers needs to be validated.

**Describe the solution you'd like**

A reusable Flask [JWT validation decorator](https://auth0.com/docs/quickstart/backend/python/01-authorization#create-the-jwt-validation-decorator) from Authlib sounds pretty ideal.

**Describe alternatives you've considered**

https://github.com/auth0-samples/auth0-python-api-samples/blob/master/00-Starter-Seed/server.py

**Additional context**

**Comment by lepture** [comment]
It won't be a feature in Authlib.
