### ISSUE TITLE
Check for Secure connection should be configurable

### ISSUE THREAD

**Issue by wildex** [lepture/authlib#185]
**Is your feature request related to a problem? Please describe.**

When I ran Flask app + Authlib behind Nginx SSL with `proxy_pass` directive, I am still getting **InsecureTransportError** exception.
This is happening because App runs inside server on the "insecure" http, while web facing Nginx uses secure HTTPS and then proxies requests.

**Describe the solution you'd like**

I know, that we can use environment variable `AUTHLIB_INSECURE_TRANSPORT=1`. But in this case transport is still secure and there should be possibility to configure library in other way to work in such stacks.
For example it can be done with some native configuration to the library.

**Additional context**

Example nginx config:

```
server {
  server_name exmple.com; 
  listen 443 ssl; 

  location / {
    client_max_body_size 0;
    gzip off;

    proxy_http_version 1.1;

    proxy_set_header    Host                $http_host;
    proxy_set_header    X-Real-IP           $remote_addr;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto   $scheme;

    proxy_pass http://localhost:5000;
  }
```

**Comment by lepture** [comment]
If you are using gunicorn, here is the configure:

https://docs.gunicorn.org/en/stable/settings.html#secure-scheme-headers

**Comment by lepture** [comment]
It is your wsgi server's responsibility to handle `wsgi.scheme`.
