### ISSUE TITLE
Unable to decode ID Token with unicode characters - Part 1

### ISSUE THREAD

**Issue by TomAtHulu** [lepture/authlib#187]
**Describe the bug**

We use Okta to authenticate.  We have employees in Beijing that include unicode characters in their profiles.  For a few employees the exchange of authentication code for tokens fails due to errors parsing the returned ID Tokens.  The first consequence that we experience is an 'Incorrect Padding' error which comes from the urlsafe_b64decode function while parsing the signature. We've gotten around that error by including a couple of '=' signs at the end of the signature.  Attached is [parse_token.py.zip](https://github.com/lepture/authlib/files/4149452/parse_token.py.zip) which illustrates this issue and our work-around.
Since the tokens themselves contain some personally identifiable information which I cannot post to the general list, please contact me separately and I can get you a few examples.
**Error Stacks**

```
Traceback (most recent call last):
  File "/Users/tom.gardner/Projects/parse-error/parse_token.py", line 44, in <module>
    signature = urlsafe_b64decode(signature)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**To Reproduce**

Run the attached python application with Python 2.7

**Expected behavior**

The application will fail with an Incorrect padding error.

**Environment:**

 - OS: MacOS
 - Python Version: 2.7
 - Authlib Version: Latest version in Git

**Additional context**

You'll have to contact me to get an ID Token to use.

**Comment by lepture** [comment]
Could you provide a test case for it?

**Comment by TomAtHulu** [comment]
> Could you provide a test case for it?

I sent a couple of examples - let me know if you have any questions about them.

**Comment by lepture** [comment]
I didn't see any example.  `parse_token.py.zip` is just python code. Please provide a minimal example to reproduce your problem.

**Comment by phy25** [comment]
@lepture I guess they send it to your email because they don't want the token to be exposed to public?

**Comment by TomAtHulu** [comment]
Yes. User names, email, client id etc.

**Comment by lepture** [comment]
No, I didn't get such emails. @TomAtHulu you need to provide example (data) for me to test it.

**Comment by lepture** [comment]
No test case to reproduce the issue. Close for now.

**Comment by xarg** [comment]
I have the same issue. I traced it to the interaction between generating the base auth [here](https://github.com/lepture/authlib/blob/master/authlib/oauth2/auth.py#L10) extracting the base auth [here](https://github.com/lepture/authlib/blob/master/authlib/oauth2/rfc6749/util.py#L34).

It's very simple to test it:

```
## this works:
(Pdb) text = '60abef515ee8b3188fb718ab:ZxH@VT7cCBKr8FCiGabEpw#sT9L5NOk#!i9n94cV~0TCLG~2C#a@p3K5uBcr8Fp8OdD11116'
(Pdb) base64.b64decode(to_native(base64.urlsafe_b64encode(to_bytes(text, 'latin1'))))
b'60abef515ee8b3188fb718ab:ZxH@VT7cCBKr8FCiGabEpw#sT9L5NOk#!i9n94cVL\x15\x10\xd3\x11\xd3$26\x14\x07\x034\xb3WT&7#\x84g\x03\x84\xf6DC\x13\x13\x13\x13`'

## this doesn't work anymore because the string seems to be too long maybe?
(Pdb) text = '60abef515ee8b3188fb718ab:ZxH@VT7cCBKr8FCiGabEpw#sT9L5NOk#!i9n94cV~0TCLG~2C#a@p3K5uBcr8Fp8OdD1111111111111116'
(Pdb) base64.b64decode(to_native(base64.urlsafe_b64encode(to_bytes(text, 'latin1'))))
*** binascii.Error: Incorrect padding

### This is yet another issue:
(Pdb) text = '60abef515ee8b3188fb718ab:ZxH@VT7cCBKr8FCiGabEpw#sT9L5NOk#!i9n94cV~0TCLG~2C#a@p3K5uBcr8Fp8OdD111111111111111111116'
(Pdb) base64.b64decode(to_native(base64.urlsafe_b64encode(to_bytes(text, 'latin1'))))
*** binascii.Error: Invalid base64-encoded string: number of data characters (149) cannot be 1 more than a multiple of 4
```

I assume it's because of the `urlsafe_b64encode` - to me it's super clear why it should be urlsafe, it's part of the `Authorization` header so it shouldn't matter if it's URL safe.

The fix [here](https://github.com/lepture/authlib/blob/master/authlib/oauth2/auth.py#L10) should be `auth = to_native(base64.b64encode(to_bytes(text, 'latin1')))` instead of `auth = to_native(base64.urlsafe_b64encode(to_bytes(text, 'latin1')))`
