### ISSUE TITLE
error w/ google oauth

### ISSUE THREAD

**Issue by aogier** [lepture/authlib#196]
Hello, I can't made a successful auth against google oauth because an error (that seems related or identical to https://github.com/authlib/loginpass/issues/47).

Here is the relevant code:

```python
config = Config(".env")  # pylint: disable=invalid-name
oauth = OAuth(config)

CONF_URL = 'https://accounts.google.com/.well-known/openid-configuration'
oauth.register(
    name='google',
    server_metadata_url=CONF_URL,
    client_kwargs={
        'scope': 'openid email profile'
    }
)

async def login(request):
    redirect_uri = request.url_for('auth')
    return await oauth.google.authorize_redirect(request, redirect_uri)

async def auth(request):
    logging.critical(request.headers)
    token = await oauth.google.authorize_access_token(request)
    user = await oauth.google.parse_id_token(request, token)
    request.session['user'] = dict(user)
    return RedirectResponse(url='/')

ROUTES = [
    Route('/login', endpoint=login),
    Route('/auth', endpoint=auth),
]

app = Starlette(debug=True, routes=ROUTES)  # pylint: disable=invalid-name
```

when `/auth` endpoint is hit after a successful authentication, I get this traceback (first line is mine):

```
[osso] CRITICAL: Headers({'host': 'osso.dev.scimmia.net', 'x-request-id': '299db1f2a6d8f187459083ed590d4adb', 'x-real-ip': '10.42.0.1', 'x-forwarded-for': '10.42.0.1', 'x-forwarded-host': 'osso.dev.scimmia.net', 'x-forwarded-port': '443', 'x-forwarded-proto': 'https', 'x-scheme': 'https', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'accept-language': 'en-US,en;q=0.5', 'accept-encoding': 'gzip, deflate, br', 'referer': 'https://accounts.google.com/', 'dnt': '1', 'upgrade-insecure-requests': '1'})
[osso] INFO:     10.42.0.1:0 - "GET /auth?state=VNyCSjjCXSojWBTqNjsm3XlxBSJEgg&code=4%2FwwEnVamW5jzr4hOz4agsa1kjrKBlCOrMJTdO0pbFM9nq9qDbJ7-riJQ4Sh9TeokDyvz47FnRtY4DQsMMNH3N_II&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=consent HTTP/1.1" 500 Internal Server Error
[osso] ERROR:    Exception in ASGI application
[osso] Traceback (most recent call last):
[osso]   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
[osso]     result = await app(self.scope, self.receive, self.send)
[osso]   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
[osso]     return await self.app(scope, receive, send)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
[osso]     await self.middleware_stack(scope, receive, send)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
[osso]     raise exc from None
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
[osso]     await self.app(scope, receive, _send)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette_authlib/middleware.py", line 122, in __call__
[osso]     await self.app(scope, receive, send_wrapper)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
[osso]     raise exc from None
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
[osso]     await self.app(scope, receive, sender)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
[osso]     await route.handle(scope, receive, send)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
[osso]     await self.app(scope, receive, send)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
[osso]     response = await func(request)
[osso]   File "./osso/app.py", line 79, in auth
[osso]     token = await oauth.google.authorize_access_token(request)
[osso]   File "/usr/local/lib/python3.7/site-packages/authlib/integrations/starlette_client/integration.py", line 58, in authorize_access_token
[osso]     return await self.fetch_access_token(**params)
[osso]   File "/usr/local/lib/python3.7/site-packages/authlib/integrations/base_client/async_app.py", line 105, in fetch_access_token
[osso]     token = await client.fetch_token(token_endpoint, **kwargs)
[osso]   File "/usr/local/lib/python3.7/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 120, in _fetch_token
[osso]     return self.parse_response_token(resp.json())
[osso]   File "/usr/local/lib/python3.7/site-packages/authlib/oauth2/client.py", line 348, in parse_response_token
[osso]     self.handle_error(error, description)
[osso]   File "/usr/local/lib/python3.7/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 76, in handle_error
[osso]     raise OAuthError(error_type, error_description)
[osso] authlib.common.errors.AuthlibBaseError: invalid_request: Missing parameter: redirect_uri
```

**Expected behavior**

A successful login via google oauth

**Environment:**

 - OS: python:3.7-slim docker image (alpine)
 - Authlib Version: 0.14.1

Thank you, ciao!

**Comment by aogier** [comment]
After digging a bit, I've found that this is a response we get from https://oauth2.googleapis.com/token, if I debug print in this function https://github.com/lepture/authlib/blob/7f4e2af155030afc6f7f1f44ebdadcaacf9a2ad5/authlib/integrations/httpx_client/oauth2_client.py#L104-L120 I can see:

```
CRITICAL: ENDPOINT: https://oauth2.googleapis.com/token
CRITICAL: url: https://oauth2.googleapis.com/token
CRITICAL: headers: {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'}
CRITICAL: auth: <authlib.integrations.httpx_client.oauth2_client.OAuth2ClientAuth object at 0x7f02282bc690>
CRITICAL: kw: {}

# this last one is the response we get from endpoint
CRITICAL: RESPJSON: {'error': 'invalid_request', 'error_description': 'Missing parameter: redirect_uri'}
```

So this seems to originate from google side. Analyzing the entire chat my browser did w/ google servers I can see that, where a `redirect_uri` is passed, there is always a correct value (ie. `my.sub.domain.tld` for a verified `domain.tld`).  

Going further will be very difficult as I'll basically to understand a lot of codebase, which I'll do anyway. Any help would greatly appreciated tho.


Thanks in advance and have a nice day

**Comment by phy25** [comment]
Probably loook at https://github.com/lepture/authlib/blob/f754eff0c21a11c837a25bc6d4a49875de243c72/authlib/integrations/base_client/base_app.py#L146?

**Comment by aogier** [comment]
@phy25 could you please elaborate a bit? Unsure on what you mean w/ your comment...

**Comment by phy25** [comment]
@aogier This is where `redirect_uri` is being generated from `fetch_access_token`. You could print the value and see if it's the same as the one when you are being redirected to Google.

**Comment by aogier** [comment]
no `redirect_uri` in my session indeed, obv if I hardcode in the file
```python
params['redirect_uri'] = my_redir_uri
```

this works. 

Less luck if I set it in my endpoints' `request.session`. So I though my drop-in session replacement middleware could be the cause, but then again no luck using vanilla SessionMiddleware.  

Honestly I don't have a clue, do you ? :) Anyway thank you a lot for pointing me out this one, I could start from it for a deeper dig...

**Comment by phy25** [comment]
Technically those session data should be saved here before you got redirected to Google:

https://github.com/lepture/authlib/blob/f754eff0c21a11c837a25bc6d4a49875de243c72/authlib/integrations/base_client/base_app.py#L153-L164

If needed I think you can just extend this class and write your own implementation against `save_authorize_data()`.

**Comment by aogier** [comment]
I'm tracing `set_session_data` and `get_session_data` and I could see something is indeed setted during login execution:

```
CRITICAL: SET SESS DATA: redirect_uri -> https://...
CRITICAL: SET SESS DATA: state -> KD...
CRITICAL: SET SESS DATA: nonce -> loi...
INFO:     10.42.0.1:0 - "GET /login HTTP/1.1" 302 Found
```

But when I hit my redirect uri, everything is lost:

```
 CRITICAL: GET SESS DATA: state -> _google_authlib_state_ -> None
CRITICAL: GET SESS DATA: code_verifier -> _google_authlib_code_verifier_ -> None
CRITICAL: GET SESS DATA: redirect_uri -> _google_authlib_redirect_uri_ -> None
```

and session is btw empty so it's not persisting for dunno what reason...

I'd try to set them during my /login endpoint but I don't know state nonce et al...

**Comment by phy25** [comment]
This case you will have to check your session/cookie. `nonce` is intended to be random per request to prevent CSRF attacks.

**Comment by aogier** [comment]
I can see via devtools in my browser that the problem is I loose the session during the trip:
1. /login
2. accounts.google.com
3. /auth

So the superbasic workaround is to encode a session value in /auth start:

```python
    request.session['_google_authlib_redirect_uri_'] = request.url_for('auth')
```

But there is something more to investigate on why session cookie that login correctly set gets then lost when we land back on pages... I'll investigate on this and let you know! Thank you!

**Comment by aogier** [comment]
I now found the culprit, that's was an error my side: session cookies w/ negative max-age that did not survived across auth flow :(((((( thank you, at least I'd learned a bit against authlib's internals and that's not bad at all! I'm sorry for the noise, ciao!

**Comment by lepture** [comment]
In case someone found this issue. There are posts to teach people set:

```
SECRET_KEY = os.urandom(16)
```

This is totally wrong. You can't set `SECRET_KEY` dynamically.

e.g. In production, there will be many workers, if you set `SECRET_KEY` dynamically, each worker will have its own secret key, workers won't share session at all.

**Comment by lepture** [comment]
@aogier We have a Google example for starlette: https://github.com/authlib/demo-oauth-client/tree/master/starlette-google-login

I didn't reproduce your problem. The starlette SessionMiddleware works well.
