### ISSUE TITLE
requests library not closing connections.

### ISSUE THREAD

**Issue by JakeDEvans** [lepture/authlib#203]
**Describe the bug**

client mode not setting keepalive or http connection close parameters causing multiple events of hanging tcp connections.

nginx error: client 172.19.0.18 closed keepalive connection (where client is the authlib client making a request)

**To Reproduce**

use authlib client against authlib server, both behind nginx proxy.

**Expected behavior**

requests parameter to close the connection, as described here: https://stackoverflow.com/questions/10115126/python-requests-close-http-connection

**Environment:**

 - OS: alpine
 - Python Version: 3.7
 - Authlib Version: 0.14.1

**Additional context**

**Comment by phy25** [comment]
Is it possible that the default `requests` behavior leads to this? If so I don't think it should be fixed on authlib end.

**Comment by lepture** [comment]
@JakeDEvans please provide a simple example to test. I have a running service which is using Authlib. It has no such a problem for 3 years.

**Comment by lepture** [comment]
close issue for now until @JakeDEvans providing a test case.
