### ISSUE TITLE
incompatibility with new httpx version

### ISSUE THREAD

**Issue by suud** [lepture/authlib#208]
**Describe the bug**

`httpx`'s public api has been updated (see https://github.com/encode/httpx/issues/772). `httpx.content_streams` is a private module, since Version `0.12.1` of `httpx`.

I'm wondering what a reliable fix would look like. Importing (from) the private module `httpx._content_streams` might break in the future.

Here, some more cases where we use `httpx` modules that are now private (there might be more):
- https://github.com/lepture/authlib/blob/f754eff0c21a11c837a25bc6d4a49875de243c72/authlib/integrations/httpx_client/oauth2_client.py#L3-L6
- https://github.com/lepture/authlib/blob/142a7e5b8d4290707808baa5b35635961bcb279a/tests/py3/utils.py#L3
**Error Stacks**

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/httpx_client/__init__.py", line 9, in <module>
    from .oauth1_client import OAuth1Auth, AsyncOAuth1Client
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth1_client.py", line 11, in <module>
    from .utils import extract_client_kwargs, rebuild_request
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/httpx_client/utils.py", line 2, in <module>
    from httpx.content_streams import ByteStream
ModuleNotFoundError: No module named 'httpx.content_streams'
```

**To Reproduce**

```python
from authlib.integrations.httpx_client import AsyncOAuth2Client
```

**Environment:**

 - OS: Debian 10 (Buster)
 - Python Version: 3.8
 - Authlib Version: 0.14.1
 - httpx Version: 0.12.1

**Comment by lig** [comment]
Could somebody teach `httpx` authors that this change should've bumped version to 0.13.0, please?

**Comment by phy25** [comment]
Not sure why @lig doesn't want to reach out, but:

> Note: HTTPX should be considered in beta. We believe we've got the public API to a stable point now, but would strongly recommend pinning your dependencies to the 0.12.* release, so that you're able to properly review API changes between package updates. A 1.0 release is expected to be issued sometime on or before April 2020.

https://github.com/encode/httpx/blob/master/README.md

**Comment by lig** [comment]
> pinning your dependencies to the 0.12.*

the fun is that 0.12.0 and 0.12.1 are incompatible

**Comment by lepture** [comment]
Please lock your httpx==0.12.0. I'm not going to fix it soon, because httpx has changed a lot of times.
