### ISSUE TITLE
ensure_active_token doesn't work for client_credentials

### ISSUE THREAD

**Issue by diogobaeder** [lepture/authlib#213]
**Describe the bug**

Currently, authlib is unable to fetch a new access token if the previous one expires when the client is using a `client_credentials` `grant_type`, because at the point it tries to fetch it, it doesn't pass along the `client_id` and `client_secret` with the request to fetch it - the `kwargs` argument is empty at this point. This leads to the Authentication Server responding with an `invalid_token` error.

**Error Stacks**

Instead of an error stack, which is not too relevant, I'll point out to the exact place where the bug is:

1. Here is where the `ensure_active_token` method uses the kwargs to fetch the token: https://github.com/lepture/authlib/blob/master/authlib/integrations/requests_client/oauth2_session.py#L28
1. And here is where the class calls that method without passing along any kwargs, which leads to the call to `fetch_token` not have any `client_id` or `client_secret`, which are necessary for `OAuth2Client._prepare_token_endpoint_body`: https://github.com/lepture/authlib/blob/master/authlib/integrations/requests_client/oauth2_session.py#L35

**To Reproduce**

To reproduce the error, first you have to have a way to expire the token that you get from the auth server. In my case, I store the token in an encrypted Redis item, so I just change it to expire in the past, but you could just wait for the token to expire too - or, if you have access to the auth server running locally, just make it expire tokens in a few seconds or so.

Then, to reproduce:
1. Make sure you have your `client_kwargs` configuration contains a `client_credentials` `grant_type`;
1. Make sure the RemoteApp has access to the access token;
1. Make a request to the data server;
1. Ensure the access token expires somehow (see above);
1. Make another request to the data server

**Expected behavior**

I expect the library to be able to fetch a new access token correctly.

**Environment:**

 - OS: Arch Linux 5.5.13-arch1-1 #1 SMP PREEMPT Wed, 25 Mar 2020 16:04:40 +0000 x86_64 GNU/Linux
 - Python Version: 3.6.10
 - Authlib Version: 0.14.1

**Additional context**

I would try to send a PR myself, but I don't know how to approach this problem yet; The thing is, it seems that it's the RemoteApp that has access to client ID and secret, but the attempt to re-fetch a token is made inside the OAuth2Client itself, so it seems that it doesn't have access to that information.

[EDIT] Just pushed a PR with the fix. I tested it locally, and it works, it fixes the issue.

**Comment by lepture** [comment]
The code itself has no problem. You need to pass `token_endpoint_auth_method="client_secret_post"` in your case. The default `token_endpoint_auth_method` is `client_secret_basic`. It seems your integration doesn't support this method.

**Comment by lepture** [comment]
```python
session = OAuth2Session(
    # .....
    token_endpoint_auth_method="client_secret_post",
)
```
