### ISSUE TITLE
Potential compliance-fix issue with Zoom refresh token headers

### ISSUE THREAD

**Issue by wgwz** [lepture/authlib#218]
**Is your feature request related to a problem? Please describe.**

The Zoom refresh token process requires a header like so:

https://marketplace.zoom.us/docs/guides/auth/oauth#refreshing

```
Authorization | The string "Basic" with your Client ID and Client Secret with a colon : in between, Base64 Encoded. For example, Client_ID:Client_Secret
```

Is this something that needs to be fixed in a compliance fix?

**Describe the solution you'd like**

If this is a non-standard issue:

https://docs.authlib.org/en/latest/client/oauth2.html#compliance-fix-for-non-standard
https://docs.authlib.org/en/latest/client/frameworks.html#compliance-fix-for-oauth-2-0

Currently we have:

- access_token_response: invoked before token parsing.
- refresh_token_response: invoked before refresh token parsing.
- protected_request: invoked before making a request.

Could we add:

- refresh_token_request: invoked before refresh token request.

**Describe alternatives you've considered**

Using protected_request and then checking if it's the URL for the refresh token. And then adding the headers. But I'm not sure if that would work.

**Comment by wgwz** [comment]
Looks like this is actually just a need of documentation updates:
https://github.com/lepture/authlib/blob/293a898839c28198ff2ae2e9366f28550ae7619c/authlib/oauth2/client.py#L327

**Comment by wgwz** [comment]
So I can access refresh_token_request, but I think I also need to be able to apply a compliance fix for getting the access token.

```
Make a POST request to https://zoom.us/oauth/token with the following query parameters and authorization header:

Query Parameter | Description
-- | --
grant_type | Value authorization_code.
code | The authorization code supplied to the callback by Zoom.
redirect_uri | Your application’s redirect URI.
```
Source: See "Getting Access Token" and Step 2: https://marketplace.zoom.us/docs/guides/auth/oauth

If someone could let me know if this is even a non-standard behavior that would be great. The reason I'm pursuing it is because I'm seeing a weird issue where during local development, where the access tokens from Zoom seem to be invalidating those in the production environment. And I'm thinking it could be related to these headers being missing in the requests.

**Comment by wgwz** [comment]
So to update this before I forget what happened. AFAICT I don't need any of these compliance hooks for Zoom. What ended up happening was that I was requesting an access token, which then invalidated the token I had stored in the database.

The only remaining issues (which I will help with) is improves to the documentation. And I also would like to contribute a loginpass setup for Zoom.

**Comment by lepture** [comment]
I'm not sure what's going on here. If you would like to contribute to the documentation, please create a PR later. I'll close this issue for now.
