### ISSUE TITLE
OpenID connect certification

### ISSUE THREAD

**Issue by jonas-weismueller-jdas** [lepture/authlib#220]
**Is your feature request related to a problem? Please describe.**

The OpenID connect foundation lists certified libraries for OP and RP.
OP: https://openid.net/developers/certified/#OPLibs
RP: https://openid.net/developers/certified/#RPLibs

**Describe the solution you'd like**

There might be an interest to test your implementation against their conformance testing tool and thus get listed as python certified OP/RP library?

Certification: https://openid.net/certification/
Certification Instructions: https://openid.net/certification/instructions/

**Comment by lepture** [comment]
It seems that I have to pay $2500 to get a certification.
