### ISSUE TITLE
Metadata not available when verify token is called

### ISSUE THREAD

**Issue by ayamani** [lepture/authlib#231]
I'm using the flask client for my project. My client is established by setting the SERVER_METADATA_URL. The setup is working fine but I've hit a blocker when making requests. The verify token is failing since the metadata seems to be empty when the ensure_active_token is called (integrations/requests_client/oauth2_session.py). The resulting token url is empty if I just use the server_meta_data when initializing the client. As a work around, I'm forced to specify the token url on addition to the metadata url on initialization.

I realized that the metadata url was being unset after the initial load, does it have something to do with that? Should the metadata be loaded again at this point?

**Comment by lepture** [comment]
@ayamani please provide a minimal test case. Your given information can't help to find what's the problem is.

**Comment by lepture** [comment]
Given there is no response for 1 month, I'll close this issue for now. If @ayamani can provide more information, he may reopen it.
