### ISSUE TITLE
Feature request: Validate Authorization header Bearer tokens issued by external oidc service

### ISSUE THREAD

**Issue by svinther** [lepture/authlib#234]
**Problem**

If having to protect an API resourceserver by verifying Authorization header accesstokens (jwt bearer tokens) issued elsewhere by oidc authentication server, it seems like a lot of work, and it would be better to have the auth library do most of it. 

**Solution I'll like**

With minimum configuration and code, be able to attach some ```@auth_required``` decorator to my endpoint functions, e.g:

``` python
@app.route("/test-bearer")
@auth_required
def r():
    user = get_session_user()
    return user
``` 

The decorator enforces verification of the presence and validity of a Authorization header bearer accesstoken.

The best solution I can come up with is like the following. It uses the oidc metadata endpoint to retrieve the public keys for verifying the accesstokens, and uses some authlib provided features for that, decoding the jwt and validating expiration etc.

Besides being a lot of work, I suspect there might be missing some important validations that should always be present.

``` python
from functools import wraps

import requests
from authlib.jose import jwt
from authlib.jose.errors import JoseError, ExpiredTokenError
from flask import Response, request, session, g

from config import Config

# Fetch the openid metadata so we may know the jwk endpoint uri
server_metadata_url = f"{Config.OIDC_CONF_BASE_URL}/.well-known/openid-configuration"
server_metadata_r = requests.get(server_metadata_url)
if server_metadata_r.status_code != 200:
    raise Exception(
        f"Error getting auth server metadata from url: {server_metadata_url}"
        + ", status_code: {server_metadata_r.status_code}"
    )
server_metadata = server_metadata_r.json()

# Fetch the public key for validating Bearer token
jwk_r = requests.get(server_metadata['jwks_uri'])
if jwk_r.status_code != 200:
    raise Exception(
        f"Error getting jwk from url: {server_metadata['jwks_uri']}"
        + ", status_code: {jwk_r.status_code}"
    )
jwk = jwk_r.json()


# Decorator enforcing that a request has a correct Authorization header with a valid Bearer accesstoken
def auth_required(f):
    """ Besides enforcing correct Bearer token, a user object is alose stored on the request context, for later
    retrieval by the application"""

    @wraps(f)
    def decorator(*args, **kwargs):
        if 'user' in g:
            raise Exception("auth_required called twice ?")

        authheader = request.headers.get("Authorization")
        if authheader and authheader.lower().startswith("bearer "):
            token_str = authheader[7:]
            token = jwt.decode(token_str, jwk)
            try:
                token.validate()
                session.user = token
                g.user = token
                return f(*args, **kwargs)
            except ExpiredTokenError as e:
                return Response(str(e), status=401)
            except JoseError as e:
                print(type(e), str(e))
                return Response(status=403)
        return Response("Bearer required", status=401)

    return decorator


def get_session_user():
    return g.user
```

This might be related to https://github.com/lepture/authlib/issues/89 from @jcassee as I think that my feature request could also be implemented as a standard ```BearerTokenValidator```

**Comment by lepture** [comment]
This should not be an Authlib function. It could be in documentation or a blog post. You may create a Flask extension yourself too. But it should not be code in Authlib.

**Comment by svinther** [comment]
Looking at the authlib.integrations.flask_client stuff that supports oidc enabled code flow authentication for "web style apps", it occured that there might as well be similar support for "api style apps" (oauth2 bearer tokens) ?

**Comment by lepture** [comment]
This is certainly not an Authlib thing.
