### ISSUE TITLE
Save and Update Tokens at OAuth Accounts level

### ISSUE THREAD

**Issue by leh08** [lepture/authlib#236]
Hi Team,

I would like to request a save and update tokens at Providers level

Currently, I want to build app that use shared tokens for example Google,.. and In google, we have like 2 accounts and everyone use them.

For now, fetch and update token just allow (name, request.user). I would like to suggest add 1 more field is (name, request.user, provider). So we can have many shared tokens with a same provider. Thank you.

Best Regards,
Giang

**Comment by lepture** [comment]
I can't quite understand this feature request. Can you show me an example in code so that I can understand what you want. For your description, I think it is your design problem.

e.g. `user` may contain a `provider` information:

```python
class User(object):
    ...
    provider = Column(String)
```

**Comment by leh08** [comment]
Hi Lepture,

It is like my company have 2 google accounts, but 20 people use them when I sign in two accounts, I want token can be updated and got correctly. Because currently oauth has register function only allow to pass name oauth.register(name, ....), not oauth.register(name, account....). So when doing it maybe I can write update or fetch token functions use both (name, account) to find token in database correctly

Thank you,
Giang Le

**Comment by lepture** [comment]
Why not:

```python
google1 = oauth.register('google1', ...)
google2 = oauth.register('google2', ...)
```

**Comment by leh08** [comment]
Hi Lepture,

I have already done it. But with my company, we have **Facebook**, **LinkedIn**, **Twitter** and Inst**a**gram for each of them, I need to write **register_google**, **register_facebook**, **register_linkedin**, **register_twitter** and import each of them with the right name.

By doing it, **create_client(name, token_filter=None)**, I just need to call **create_client('google', token_filter = { 'account': 'master.account.1@gmail.com' })**. It is cleaner. Otherwise, I will need to custom it like **register(name + '_' + account_name)** and then **create_client(name + '_' + account_name)**.

And when display on drop down in token selector in My app Google source page. a name of a token when displays, it will be 'google_master.account.1@gmail.com'. When staff on ready even on Google Page, instead of 'master.account.1@gmail.com'.

Best regards

**Comment by leh08** [comment]
Hi Lepture,

I should not post a request unthoughtfully. A refresh token function in a module is used during the user process session of login and authorization. after getting token, I can just store it and use anytime I want there was no need to make the parameter to increase complexity. Thank you.

Kind regards
Giang
