### ISSUE TITLE
Unauthorized Client error 

### ISSUE THREAD

**Issue by samib6** [lepture/authlib#237]
I am having the oidc provider and client in django.
I have followed the flask example code for making the oidc provider from the example code itself.

The provider successfully redirects back to the client with an authorization code and state .I send a post request to fetch the token and then I get an unauthorized client error on my client side.
and a bad request error on the provider side (error code =400).

Providers views.py
`def authorize(request):
 
    user = request.user
    print('user:',user)
    if not user or request.user.is_anonymous:
        return redirect('oauth_login')
    if request.method == 'GET':
        try:
            #print(request)
            grant = server.validate_consent_request(request,end_user=user)
            print('grant is :',grant)
            context = dict(grant=grant, user=request.user)

        except OAuth2Error as error:
            print('error')
            return JsonResponse(dict(error.get_body()))

        return render(request, 'authorize.html', context)
  
    confirmed = request.POST['confirm']
    
    if confirmed:
        # granted by resource owner
        print('user_confirmed authorization')
        val = server.create_authorization_response(request, grant_user=request.user)
     
        return val

    # denied by resource owner
    print('out here')
    return server.create_authorization_response(request, `grant_user=None)`

Client Views.py
`def home(request):
    user = request.session.get('current_user')
    print('client user: session',user)

    if user:
        user = json.dumps(user)
    return render(request, 'home.html', context={'user': user})

def login(request):
    eyantra = oauth.create_client('eyantra')
    redirect_uri = "https://127.0.0.2:8001/authorize"

    return eyantra.authorize_redirect(request,redirect_uri)
    #return HttpResponse("login")

def auth(request):
    print('inside callback')
    #eyantra = oauth.create_client('eyantra')
    token = oauth.eyantra.authorize_access_token(request,verify=False)
    print('token is :',token)
    user = oauth.eyantra.parse_id_token(request, json.loads(token))
    request.session['user'] = user
    return redirect('/')

def logout(request):
    request.session.pop('user',None)
    return redirect('/')`

Help will be much appreciated and valued .
Thanks !

**Comment by lepture** [comment]
@samib6 please format your issue with correct Markdown. It is not readable.

**Comment by samib6** [comment]
So mistake was incorrect grant type .I changed that and its working .(Sorry for the incorrect format )
