### ISSUE TITLE
Allow Developers to use encrypted public and private keys for JWT

### ISSUE THREAD

**Issue by moswil** [lepture/authlib#238]
**Is your feature request related to a problem? Please describe.**
- When using `jwt.encode(header, payload, key)`, if the key is protected using a paraphrase, an error is thrown. This is because when creating the classes `authlib.jose.rfc7518._backends._key_cryptography.RSAKey` and 'authlib.jose.rfc7518._backends._key_cryptography.ECKey`, when calling `load_pem_private_key` method of `cryptography.hazmat.primitives.serialization.load_pem_private_key` the `password arg` is passed as `None` by default and the developer of `authlib` is not given an option to pass in a password.

**Describe the solution you'd like**
- Allow the developers to use password-protected keys
![Screenshot from 2020-06-16 03-07-12](https://user-images.githubusercontent.com/37577645/84717681-3ac64080-af7f-11ea-8184-764db8588361.png)
![Screenshot from 2020-06-16 03-06-30](https://user-images.githubusercontent.com/37577645/84717684-3d289a80-af7f-11ea-9125-f850e5c386a9.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by lepture** [comment]
With our master code, you can do this:

```py
from authlib.jose import JsonWebKey

with open('key.pem', 'rb') as f:
    key = JsonWebKey.import_key(f.read(), {'password': 'xxxx'})
```

Then you can pass this `key` to `jwt`.

**Comment by moswil** [comment]
Okay, thank you.
Do you think the issue is still valid or you can close it?
