### ISSUE TITLE
Allow ssl verify = False on load_server_metadata (client)

### ISSUE THREAD

**Issue by christian-hawk** [lepture/authlib#239]
I`m using Flask integration.

I always receive the SSL error when try to fetch metadata from a test OP that uses a self-signed certificate, then I receive the SSL error.

Checking the package, I found:
`remote_app.py:20: in load_server_metadata`
tracing back to
`oauth2_session.py:113: in request`

when I call `authorize_redirect(https:.....)`, never works.

I hardcoded the oauth2_session.py that uses request from requests module the argument `verify = False`, so it works.

If there isn't any other way to do it, I would like to submit this feature requests. Also opened to workarounds.

Thanks

**Comment by michaelmolino** [comment]
You could try `export CURL_CA_BUNDLE=""` in your environment.

**Comment by christian-hawk** [comment]
Thanks @michaelmolino , this workaround worked!

Also found more info about `export CURL_CA_BUNDLE=""` on this [Stackoverflow](https://stackoverflow.com/questions/48391750/disable-python-requests-ssl-validation-for-an-imported-module), in case any user gets in this issue page with the same problem as me, and wants to know more about it.

I would like to keep this issue as an enhancement request, if team does not agree to change the code, would be nice to have `export CURL_CA_BUNDLE=""` option documented in docs.

Best,
Chris

**Comment by lepture** [comment]
Thanks @michaelmolino 

@christian-hawk I'd like to accept it into documentation. You may create a PR for it.

**Comment by christian-hawk** [comment]
sure, @lepture . 

What doc file do you suggest? maybe 'client/request.rst', 'client/index.rst'?

**Comment by lepture** [comment]
I think `client/request.rst` would be good.
