### ISSUE TITLE
Support response_mode=web_message

### ISSUE THREAD

**Issue by lehainam-dev** [lepture/authlib#243]
Hello lepture,
Thank you for building and maintaining Authlib.

**Is your feature request related to a problem? Please describe.**

I often use OAuth2 for my single page application (mostly written in React). To persist user's session, I use silent exchange flow: open an iframe with the URL of authorization request with `prompt=none` parameter. If the user still has session in the OAuth server, it will redirect `code` and `state` values in the iframe, so the client can use `code` to continue exchange new `token`. Here are the problems:
- The flow depends on client source logic: what if on load, my SPA remove all query string?
- Besides getting `code` and `state` values for token exchange flow, the iframe also loads unnecessary components, such as fonts, js libs, other ajax requests.

I aware that the client should make a specific route (`/oauth/callback`) to handle only Authorization response, but it may difficult to apply to all SPA clients. And I often use `/` as the default `redirect_uri` (because I do want my user to redirect to the home page after logged in).

**Describe the solution you'd like**

Here is a [**draft** specification](https://tools.ietf.org/html/draft-sakimura-oauth-wmrm-00) that defines a new response mode: web_message. It uses HTML5 Web Messaging instead of the redirect to return Authorization response. The response from a valid authorization request is small piece of HTML with JS handle postMessage to return authorization response to the main window.

**Additional context**

I would love to hear about your thoughts on this specification, and if you are interested in including this feature in Authlib.

If it would be welcomed, I would be happy to make a pull request to support simple mode in the spec.

Sorry if my expression is confused or unnecessary long and complicated, I have a hard time written in English.

Have a great day!

**Comment by lepture** [comment]
From my understanding, this draft is not accepted by OAuth Working Group. It is expired April 20, 2016.
