### ISSUE TITLE
Add more specificity to docstrings

### ISSUE THREAD

**Issue by YPCrumble** [lepture/authlib#244]
Currently in the docstrings I see various references to sections of what I presume is the documentation - see the image below for an example. Are these outdated or am I just not able to find them? Thanks for any help!

![image](https://user-images.githubusercontent.com/12019216/85449301-94bd9c00-b565-11ea-9893-67e6f53f6f46.png)

**Comment by phy25** [comment]
Could you attach a link to where you are refering to? Those might be sections in the specific RFC.

**Comment by YPCrumble** [comment]
@phy25 this is the section in my screenshot: https://github.com/lepture/authlib/blob/master/authlib/oauth2/rfc6749/grants/authorization_code.py#L60

**Comment by lepture** [comment]
You can find them on RFC6749.
