### ISSUE TITLE
id_token always returned with access_token despite response type being 'code' 

### ISSUE THREAD

**Issue by cutenarwhal** [lepture/authlib#246]
I have set up an OIDC provider using the Authlib OIDC provider example.  And defined an OIDC client with response type of 'code' only, with scope 'openid profile' as shown from this database screenshot: 

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/40391421/85587048-64b4ec80-b67c-11ea-8997-7eb44cacd60f.png">

The OIDC flow proceeds as one would expect except that when the client exchanges the 'code' with the token URL, an 'id_token' is returned in addition to the access_token as shown here: 

<img width="667" alt="image" src="https://user-images.githubusercontent.com/40391421/85586251-b8730600-b67b-11ea-8d49-3998b09d3774.png">

How can we prevent the id_token from appearing in this ?  So that only the access_token is returned and the client then can make a separate request for the userinfo. 

In terms of code, I'm basically running the sample OIDC provider.  https://docs.authlib.org/en/latest/flask/2/openid-connect.html

Thank you very much

**Comment by cutenarwhal** [comment]
So I see that Authlib always adds `id_token` due to [OpenIDCode.process_token](https://github.com/lepture/authlib/blob/master/authlib/oidc/core/grants/code.py)

```
    def process_token(self, grant, token):
        scope = token.get('scope')
        if not scope or not is_openid_scope(scope):
            # standard authorization code flow
            return token

        request = grant.request
        credential = request.credential

        config = self.get_jwt_config(grant)
        config['aud'] = self.get_audiences(request)
        config['nonce'] = credential.get_nonce()
        config['auth_time'] = credential.get_auth_time()

        user_info = self.generate_user_info(request.user, token['scope'])
        id_token = generate_id_token(token, user_info, **config)
        token['id_token'] = id_token
        return token
```

Implementing the process_token() with the following changes (see comments) n your OpenIDCode implementation will achieve this as follows

```
from authlib.oidc.core.grants.util import generate_id_token, is_openid_scope

class AuthorizationCodeGrant(_AuthorizationCodeGrant):

    def process_token(self, grant, token):
        scope = token.get('scope')
        if not scope or not is_openid_scope(scope):
            # standard authorization code flow
            return token
        request = grant.request
        credential = request.credential
        config = self.get_jwt_config(grant)
        config['aud'] = self.get_audiences(request)
        config['nonce'] = credential.get_nonce()
        config['auth_time'] = credential.get_auth_time()
        user_info = self.generate_user_info(request.user, token['scope'])
        # NEW: check for id_token in response_types to add it conditionally. 
        client = request.client
        response_types = client.response_types
        if 'id_token' in response_types:
            id_token = generate_id_token(token, user_info, **config)
            token['id_token'] = id_token
        return token
```

However, shouldn't this be the core behaviour anyway and not require users to subclass it?  Currently the Authlib OIDC implementation is not obeying response types I think. 

Shall I submit a PR ?

**Comment by lepture** [comment]
According to the spec: https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowSteps

`id_token` will always be there. If you don't want to add a `id_token`, you should not send `openid` scope.
