### ISSUE TITLE
Inconsistency licence statements between README and LICENSE

### ISSUE THREAD

**Issue by jorgecarleitao** [lepture/authlib#247]
The README states

```
License

Authlib offers two licenses:

    BSD for open source projects
    Commercial license for closed source projects
```

however, the LICENSE is a BSD license, which is compliant with closed source (redistribution). As it stands, I read this as

> If I develop a close source project, I must buy a commercial license; if it is an open source, I can use BSD.

If this is the case, then this project *is not* BSD licensed, as its actual license is

> If usage in open source, you can use it under the terms of BSD; else, you must buy a commercial license

I propose that we clarify what exactly do we mean with `Commercial license for closed source projects`.

**Comment by lepture** [comment]
I've removed the enforcement on readme. https://github.com/lepture/authlib/commit/6c78efc2c949df3ce9a82006986817695adf0edd

**Comment by jorgecarleitao** [comment]
Wow, thanks a lot for the fast response and fix. Much appreciated.

**Comment by papb** [comment]
Hello @lepture @jorgecarleitao, can you further clarify this please?

For a moment, I was still thinking the same as written by @jorgecarleitao:

> If I develop a close source project, I must buy a commercial license; if it is an open source, I can use BSD.

However, after [this](https://github.com/lepture/authlib/issues/247#issuecomment-652411341), my current understanding changed to:

> If I develop a closed-source project, I have two options:
> - I can use Authlib under BSD
> - I can buy a commercial license to have more benefits

Is my new understanding correct?

**Comment by v3ss0n** [comment]
I am wondering why there is still a commercial license . If thats not the case then it should be removed.

**Comment by bjmc** [comment]
> I am wondering why there is still a commercial license 

Many companies choose to financially support open source projects in order to help sustain their development or to receive direct support or benefits.

**Comment by v3ss0n** [comment]
Some orgs , especially big-tech are very serious on licenses and this would cause this great lib to get not adopted. I think you can remove and still offer commercial license by placing a link , to the webpage ?  That way it will be a lot more easier for companies to adopt. Now it sound like the are are some catches inside,

**Comment by bjmc** [comment]
If your lawyers are skittish, even more reason for them to buy a commercial license and remove any possibility of problems.

**Comment by v3ss0n** [comment]
1 . Not  a company
2 . We are choosing an auth library in an opensource  webframework and maintainers wants an auth solution that is license compatible , and adoptable to the mass.

**Comment by bjmc** [comment]
https://github.com/lepture/authlib/blob/master/LICENSE

:man_shrugging:

**Comment by v3ss0n** [comment]
i aware of that , there are 2 license . 
Existance of this already is a red flag for most companies. 
https://github.com/lepture/authlib/blob/master/COMMERCIAL-LICENSE

**Comment by bjmc** [comment]
I don't know what to tell you. You're asking @lepture to give up some of their livelihood to perhaps make some corporate attorneys somewhere more comfortable about profiting from their work without contributing back.

That's a decision for @lepture to make for themselves, but personally I think it is very audacious for you ask.

**Comment by v3ss0n** [comment]
All i wanted to point out is :
- its confusing  to have a commercial licenses
- @lepture  can put gh sponsor or many other crowd funding setups.
- also placing a link to website for commercial support license is a better idea  instead of an extra license.
