### ISSUE TITLE
Support both authorization code with and without PKCE?

### ISSUE THREAD

**Issue by quaxsze** [lepture/authlib#249]
We are using Authlib on out project Udata to authenticate third party app, most of them by authorization code.
We are implementing the PKCE flow. We would like to be able to support both authorization code with and without PKCE, in order for existing apps to continue working, and new ones to use PKCE.

Is this actually possible with authlib? The documentation does not seem to allow it.

Supporting both options depending on if the client sends a code challenge or not to the authorize endpoint would seem feasible?

**Comment by lepture** [comment]
@quaxsze It is already working in this way:

https://github.com/lepture/authlib/blob/master/authlib/oauth2/rfc7636/challenge.py#L89

And if you want to support none-PKCE for public client with `none` authentication method, you can use:

```python
CodeChallenge(required=False)
```

**Comment by quaxsze** [comment]
Okey my bad! Thank you a lot for the answer.
