### ISSUE TITLE
Support both JSON and form data

### ISSUE THREAD

**Issue by quaxsze** [lepture/authlib#254]
The actual method to handle the token endpoint according to the doc and the example server seems to be something like this:
```
@blueprint.route('/token', methods=['POST'])
def access_token():
    return oauth.create_token_response()
```

This method handles form data as it calls the `create_oauth_request` with the argument `use_json` set to `False`.
`def create_oauth_request(request, request_cls, use_json=False)`

A way to handle JSON data is to override the Authorization server and its method `create_oauth2_request` to call the one above with `use_json=True`

Like this:
```
class AuthServer(AuthorizationServer):
    def __init__(self, query_client=None, save_token=None):
        super().__init__(
            query_client=query_client,
            save_token=save_token,
        )

    def create_oauth2_request(self, request):
        return create_oauth_request(request, OAuth2Request, use_json=True)
```

But handling both and switching according to the incomming request's format is complicated.
Can be done in such a way:
```
@blueprint.route('/token', methods=['POST'])
def access_token():
    has_form = bool(request.form)
    req = create_oauth_request(request, OAuth2Request, use_json=not has_form)
    return oauth.create_token_response(request=req)
```
But it feels silly to call a method that will be called again 2 levels after.
It would be nice to have an elegant way to achieve this, if it does not already exists.

**Comment by lepture** [comment]
It is really not a good idea to accept json payload in OAuth token endpoint. According to https://tools.ietf.org/html/rfc6749, you should send payload in `application/x-www-form-urlencoded`.

With your implementation, there will be one more non-compliance OAuth 2.0 provider. Authlib respects the standard, it will not provide such a method out of the box.

However, if you want, you can still create such a non-compliance provider by re-write the `create_oauth2_request` method.

**Comment by lepture** [comment]
Also, it seems a duplicate issue to https://github.com/lepture/authlib/issues/156

**Comment by quaxsze** [comment]
Thank you for the answer it is very clear as always!
