### ISSUE TITLE
Supporting pre-releases on pypi

### ISSUE THREAD

**Issue by Cellebyte** [lepture/authlib#258]
**Is your feature request related to a problem? Please describe.**

It is currently very complex to develop against the new API from master. 

**A clear and concise description of what you want to happen.**

It would be better to also support some kind of pre-release to not need a direct install of the source code from master. It definitely makes development and automated testing easier without keeping eyes on commit shas.

**Comment by lepture** [comment]
We are going to release v0.15 soon, in about 2 weeks.

**Comment by bjmc** [comment]
@lepture Early-access to pre-release builds sounds like exactly the kind of feature companies might want to [pay for as part of a commercial plan.](https://authlib.org/plans)

**Comment by kerrermanisNL** [comment]
Hey there. Any update on this? Would like to continue with a conversion to authlib, but waiting on `v0.15` before that can continue :)

**Comment by kerrermanisNL** [comment]
Bump :)

**Comment by lepture** [comment]
v0.15 is released.

**Comment by kerrermanisNL** [comment]
Awesome, thanks guys :+1:
