### ISSUE TITLE
Should password grant flow require client id and secret?

### ISSUE THREAD

**Issue by nggary** [lepture/authlib#26]
I am working on the password grant flow and I found that the library require me to put client id and secret into header even I am using password grant flow, otherwise it would return "invalid_client" as response. Is this a mistake?

**Comment by lepture** [comment]
@nggary https://tools.ietf.org/html/rfc6749#section-4.3.2

> If the client type is confidential or the client was issued client
> credentials (or assigned other authentication requirements), the
> client MUST authenticate with the authorization server as described
> in Section 3.2.1.

BTW, this is an issue tracker. If you have questions, please ask it on StackOverflow: https://stackoverflow.com/questions/tagged/authlib
