### ISSUE TITLE
你好！用authlib做阿里钉钉的第三方登录功能的时候

### ISSUE THREAD

**Issue by kanhebei** [lepture/authlib#263]
今天做阿里钉钉的时候，，
钉钉的请求接口用的字段不是client_id而是appid字段，
这样的结果就是调用auth.dingding.authorize_redirect()生成的url中client_id在钉钉的接口中是无效的

我想寻求的帮助是。。如何把client_id变成appid

**Comment by lepture** [comment]
You can use `authorize_params`:

```py
oauth.register(
  name='dingding',
  authorize_params={'appid': 'xxx'},
  ...
)
```

Please ask help in StackOverflow.
