### ISSUE TITLE
Missing required parameter: response_type

### ISSUE THREAD

**Issue by JamieQeexo** [lepture/authlib#288]
**Describe the bug**

Hi, we are seeing this intermittent Auth0 issue from one of our flask applications, "Missing required parameter: response_type". We do not send `response_type` via neither `metadata` nor `kwargs`. Therefore, it should just be supplied `'code'`. We are wondering if the root of this issue could be on our end. 

**Error Logs**

```
{
"date": "2020-10-29T07:12:57.995Z",
"type": "f",
"description": "Missing required parameter: response_type",
"connection_id": "",
"ip": IP,
"user_agent": "Other 0.0.0 / Other 0.0.0",
"details": {
"body": {},
"qs": {},
"error": {
"message": "Missing required parameter: response_type",
"oauthError": "invalid_request",
"type": "request-error"
}
},
"hostname": OUR_HOST_NAME
"log_id": "90020201029071303317000567544959084225084138735571828754",
"_id": "90020201029071303317000567544959084225084138735571828754",
"isMobile": false
}
```

**Expected behavior**

`response_type` should not be missing from the authorization URL.

**Environment:**

 - OS: Amazon Linux
 - Python Version: 3.7.x
 - Authlib Version: 0.14.3

**Additional context**

This is how we set up in our codebase:
```
auth0 = OAuth(app).register(
    'auth0',
    client_id=SETTINGS.auth0_client_id,
    client_secret=SETTINGS.auth0_client_secret,
    api_base_url=SETTINGS.auth0_custom_url,
    access_token_url=f'{SETTINGS.auth0_custom_url}/oauth/token',
    authorize_url=f'{SETTINGS.auth0_custom_url}/authorize',
    client_kwargs={
        'scope': 'openid profile email',
    },
)
```

```
# A function to redirect to the Auth0 login page 
return auth0.authorize_redirect(redirect_uri=_server_url('/login_callback'),
                                state=nonce,
                                **query_parameters) # `response_type` not included
```

**Comment by lepture** [comment]
@JamieQeexo according to our code: https://github.com/lepture/authlib/blob/master/authlib/oauth2/client.py#L136

You can see, if there is no defined `response_type`, the default value is `code`.
