### ISSUE TITLE
OAuth2ClientMixin requires a client_secret

### ISSUE THREAD

**Issue by ivonnemclaughlin** [lepture/authlib#29]
1. From https://play.authlib.org/ 
2. Select Apps
3. Select New Oauth2 Client
4. Fill in the fields without checking the box Confidential Client
5. Click Create

You get:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Seems like this is due to OAuth2ClientMixin requiring a client secret

**Comment by lepture** [comment]
@ivonnemclaughlin thanks for your report.
