### ISSUE TITLE
Incorrect authorization error responses

### ISSUE THREAD

**Issue by nsklikas** [lepture/authlib#291]
**Describe the bug**
All the authorization error response in the code flow have status `400` and don't contain the `state` parameter.
According to the spec https://tools.ietf.org/html/rfc6749#section-4.1.2.1:
The `state` parameter is mandatory.
In addition the provider should only return 400 if the redirect URI is unknown, e.g. the `client_id` is unknown or the `redirect_uri` doesn't match the `client_id `.

**Comment by lepture** [comment]
@nsklikas I don't understand your problem

The state parameter is mandatory

> REQUIRED if a "state" parameter was present in the client authorization request.

If the client doesn't provide a `state`, the provider will not return a state.

**Comment by nsklikas** [comment]
Yes the state parameter is mandatory meaning that it MUST be added if one existed in the authorization request.

This doesn't happen in the current authlib version.

**Comment by nsklikas** [comment]
Also what about

> In addition the provider should only return 400 if the redirect URI is unknown, e.g. the client_id is unknown or the redirect_uri doesn't match the client_id .

?
