### ISSUE TITLE
Twitter OAuth Not working due to missing 'request_token' parameter

### ISSUE THREAD

**Issue by hashcutdev** [lepture/authlib#294]
**Describe the bug**

```oauth.twitter.authorize_access_token(request)``` is normally called in the callback function. The ```request``` object usually has a request_token parameter in its query parameters. However, Twitter's 3-legged OAuth process, described here:
https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens

Does not return a request_token parameter. Instead it returns `oauth_token` and `oauth_verifier`. Both of these are expected to be passed back to the twitter's auth endpoint to get the user's tokens.

The problem comes in function `fetch_access_token` in authlib\integrations\base_client\async_app.py. That function contains the following code:
```
                if request_token is None:
                    raise MissingRequestTokenError()
                # merge request token with verifier
                token = {}
                token.update(request_token)
                token.update(params)
                client.token = token
```

Since twitter doesn't have a `request_token`, the `MissingRequestTokenError()` is raised and the authorize process fails.
This is an error for twitter because twitter doesn't require a request_token. I commented out the lines 1, 2, and 5 from above, and then twitter oauth worked fine, returning the client's token as expected.

FWIW, I use loginpass but this defines the twitter metadata the same as is shown in the examples, so I don't think that's the source of the error.

Is there a way to specify that for twitter, this function should just skip the request_token parameter? More generally, is there a way to specify what query parameters are expected to be returned for each endpoint, so that in the future, other endpoints that return non-standard parameters can be accommodated?

**Error Stacks**

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\fastapi\applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\starlette\middleware\sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\fastapi\routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\fastapi\routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\app\api\api_v1\endpoints\link_accounts.py", line 156, in auth_twitter
    token = await oauth.twitter.authorize_access_token(request)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\authlib\integrations\starlette_client\integration.py", line 64, in authorize_access_token
    return await self.fetch_access_token(**params)
  File "C:\Users\mraju\PycharmProjects\api-server-useraccounts\venv\lib\site-packages\authlib\integrations\base_client\async_app.py", line 90, in fetch_access_token
    raise MissingRequestTokenError()
authlib.integrations.base_client.errors.MissingRequestTokenError: missing_request_token: 
```

**To Reproduce**

```
@router.get('/twitter/login')
async def login_twitter(request: Request) -> Any:
    redirect_uri = request.url_for('auth_twitter')
    return await oauth.twitter.authorize_redirect(request, redirect_uri)


@router.get('/twitter/callback')
async def auth_twitter(request: Request):
    token = await oauth.twitter.authorize_access_token(request)
```

**Expected behavior**

**Environment:**

 - OS: Windows
 - Python Version: 3.9.0
 - Authlib Version: 0.15.2

**Additional context**

**Comment by lepture** [comment]
We have a running Twitter demo for starlette: https://github.com/authlib/demo-oauth-client/tree/master/starlette-twitter-login

My guess is that you didn’t add the session middleware.

**Comment by hashcutdev** [comment]
Thanks @lepture for the quick reply. I did add the session middleware in my code, and other oauth endpoints like google and discord work fine.

I tried the demo script you linked to, just copy/pasted it into a new file and ran it and still ran into the same error. The only change I made was to change the callback URL to match what I registered on my twitter app.

Was the twitter integration designed for their 3-way oauth process? Twitter described 3 different auth processes on their website, OAuth1, OAuth2, and 3-way OAuth. I'm using the 3-way OAuth, and haven't tried the other ways.

The only other caveat is that I'm importing starlette version 0.13.6 since this is what's compatible with the current version of fastapi. So not sure if that might affect things.

**Comment by Sebsebzen** [comment]
I'm also still encountering this bug for my Twitter login. Please re-open this issue.

**Comment by lepture** [comment]
Could you provide a runnable example for me to reproduce? Can you run the starlette demo without any change? Just add your client id and secret in the .env file.

**Comment by Sebsebzen** [comment]
It would take a while to reproduce, I can see through sentry.io that the error occurs with some of the logins. But it's exactly the same issue that @hashcutdev encountered. He also stated that he tried running the demo script and still encountered it. So, I was wondering why the issue was closed already.

The only thing that seems to be working, is @hashcutdev advice of commenting out the respective lines in the library itself under `fetch_access_token `function.

**Comment by hashcutdev** [comment]
> Could you provide a runnable example for me to reproduce? Can you run the starlette demo without any change? Just add your client id and secret in the .env file.

That's exactly what I did, except I had to make two changes in order to match the callback URL I have registered with twitter:

1. manually specify redirect_uri (request.url_for('auth') returns 'localhost' as the host. Twitter doesn't allow that as a callback host. You have to use 127.0.0.1, so I manually create the string. But I did check the output of request.url_for('auth') and aside from switching localhost to 127.0.0.1, it's otherwise the same)
2. Change uvicorn.run to use port 8000 instead of 5000

I also have in my .env file:
TWITCH_CLIENT_ID=<client-id>
TWITCH_CLIENT_SECRET=<secret>

I'm pasting my entire test file below, but you can see it's from the demo:

```
import json
from starlette.applications import Starlette
from starlette.config import Config
from starlette.requests import Request
from starlette.responses import HTMLResponse, RedirectResponse
from starlette.middleware.sessions import SessionMiddleware
from authlib.integrations.starlette_client import OAuth

app = Starlette()
app.add_middleware(SessionMiddleware, secret_key="!secret")

config = Config('.env')
oauth = OAuth(config)

oauth.register(
    name='twitter',
    api_base_url='https://api.twitter.com/1.1/',
    request_token_url='https://api.twitter.com/oauth/request_token',
    access_token_url='https://api.twitter.com/oauth/access_token',
    authorize_url='https://api.twitter.com/oauth/authenticate',
)


@app.route('/')
async def homepage(request: Request):
    user = request.session.get('user')
    if user:
        data = json.dumps(user)
        html = (
            f'<pre>{data}</pre>'
            '<a href="/logout">logout</a>'
        )
        return HTMLResponse(html)
    return HTMLResponse('<a href="/login">login</a>')


@app.route('/api/v1/link-accounts/twitter/login')
async def login(request: Request):
    redirect_uri = 'http://127.0.0.1:8000/api/v1/link-accounts/twitter/callback'
    return await oauth.twitter.authorize_redirect(request, redirect_uri)


@app.route('/api/v1/link-accounts/twitter/callback')
async def auth(request: Request):
    token = await oauth.twitter.authorize_access_token(request)
    url = 'account/verify_credentials.json'
    resp = await oauth.twitter.get(
        url, params={'skip_status': True}, token=token)
    user = resp.json()
    request.session['user'] = dict(user)
    return RedirectResponse(url='/')


@app.route('/logout')
async def logout(request):
    request.session.pop('user', None)
    return RedirectResponse(url='/')


if __name__ == '__main__':
    import uvicorn
    uvicorn.run(app, host='127.0.0.1', port=8000)

```

And again, running this through the debugger, the request that twitter sends to the callback endpoint appears to be valid i.e. conforms to the specs they laid out in their documentation. The problem appears to be in the handling of that request in the `oauth.twitter.authorize_access_token` function call.

**Comment by Sebsebzen** [comment]
@hashcutdev Did your hot fix of commenting out the lines as described in your initial post work so far? If so, you could create a fork of the authlib library with these modifications for the people affected by this bug.

**Comment by lepture** [comment]
@hashcutdev I just re-run the demo, it works just fine. I can't reproduce your problem.

In your description:

> The problem comes in function fetch_access_token in authlib\integrations\base_client\async_app.py. That function contains the following code:

This is not true. `.authorize_access_token` will call `.retrieve_access_token_params` at first, and in this `.retrieve_access_token_params`, this function will collect the `request_token` from session.

Checkout the logic:

1. **authorize_access_token**: https://github.com/lepture/authlib/blob/master/authlib/integrations/starlette_client/integration.py#L56
2. **retrive request token**: https://github.com/lepture/authlib/blob/master/authlib/integrations/base_client/base_app.py#L142

My guess is your `framework session` is not working well.

**Comment by Sebsebzen** [comment]
@lepture That doesn't explain my error happening during the same 3-way Twitter OAuth though. It's not easy to reproduce since it doesn't affect all logins. My guess it could be something related to Twitter API upgrading from v1.1. to v2.

Could you have a look at the sentinel report I linked?

**Comment by lepture** [comment]
@Sebsebzen your case could be caused by lost of session. Since I can't inspect the parameters in your shared sentry link, you can inspect it in your sentry dashboard:

```
token = self.fetch_access_token(**params)
```

What the `params` is? I think there is no `request_token` in this params. Your case is different than the issue author, the author can reproduce it always (which I don't know why).

Here are my guess for your case:

1. end user opened multiple tabs
2. one tab is authorized, `request_token` in session will be cleaned
3. end user authorize in another tab, however the session is cleaned, there is no request token

Maybe like: https://github.com/lepture/authlib/issues/285

**Comment by Sebsebzen** [comment]
@lepture That could be an explanation. 'params are filtered out but I will set up and environment where I can catch them and then report back. Thanks!

**Comment by hashcutdev** [comment]
@Sebsebzen I'm hesitant to make a fork with those lines commented out because I don't know if that might have regressions in other OAuth providers that people might be depending on. I'd hate to introduce some sort of security bug without fully understanding where the problem actually lies :-) Either way, it's pretty easy for someone to comment it out themselves if they really want to as a temporary measure.

@lepture thanks for the suggestions. I don't know why my session wouldn't be working especially with the code I posted which is essentially a cut/paste of the demo code. I'll try tracing through the debugger again and see if I can see if the session is indeed being dropped. Is there something I could look for within the request object that would tell me if the session is valid or invalid?

**Comment by ikazame** [comment]
I also faced the same problem where the request_toekn was not saved in the framework.session.
I found out that the reason was that I had set the Callback URI as "127.0.0.1", even though I was hosting the app on "localhost".
If anyone else is having the same problem, please check this cause as well.
