### ISSUE TITLE
Invalid Authorization error response

### ISSUE THREAD

**Issue by nsklikas** [lepture/authlib#299]
**Describe the bug**
According to https://tools.ietf.org/html/rfc6749#section-4.1.2.1

The authorization server should return 400 to the user only if the `client_id` or the `redirect_uri` is incorrect, otherwise the server should redirect the user back to the client with the error encoded in the URL.

In addition if the authorization request contained a `state`, then the same state value MUST be added in the error response.

To my experience authlib always returns 400 and the state is never added in the code flow.

**Expected behavior**
The `state` MUST always be added in the error response (if one was provided).

If a valid client_id/redirect_uri pair was provided then the error response MUST redirect the user back to the client (instead of returning status `400` it must return status `302`).

**Comment by lepture** [comment]
Can you provide an example to reproduce your problem? The `state` is in the location from our test case:

https://github.com/lepture/authlib/blob/master/tests/flask/test_oauth2/test_authorization_code_grant.py#L75

**Comment by nsklikas** [comment]
For example the test:
```
    def test_create_authorization_response2(self):
        server = self.create_server()
        self.prepare_data()
        data = {'response_type': 'token', 'client_id': 'client', 'state': 'aba'}
        request = self.factory.post('/authorize', data=data)

        resp = server.create_authorization_response(request)
        self.assertEqual(resp.status_code, 302)
        self.assertIn('error=access_denied', resp['Location'])
        self.assertIn('state=aba', resp['Location'])
```
Fails for 2 reasons `resp.status_code = 400` and `state` is not in `resp`

**Comment by lepture** [comment]
RFC about this part is not clear. In our implementation, the logic is:

1. find the right `Grant` instance at first
2. call `grant.validate_xxx_request`

At `get_authorization_grant` moment, we don't validate at all. Since the given response type has no supported `Grant`, we will just raise an `unsupported` error.

But, it seems Authlib raised a wrong error. It should raise `unsupported_response_type`.
