### ISSUE TITLE
Slack V2 OAuth 2.0 needs `user_scope` as part of the URL

### ISSUE THREAD

**Issue by boertel** [lepture/authlib#300]
The V2 OAuth 2.0 Slack authentication introduces 2 kind of scopes:
- `scope`: for installing an App on a workspace (getting a bot token, etc)
- `user_scope`: for sign in an user

More about slack authentication: https://api.slack.com/authentication/oauth-v2#asking

The issue is that authlib is limiting what parameters will be passed down to the authorization URL here:
https://github.com/lepture/authlib/blob/f754eff0c21a11c837a25bc6d4a49875de243c72/authlib/oauth2/client.py#L44

If I monkey patch the list to add that `user_scope` and 
```python
from authlib.oauth2 import client

client.OAuth2Client.EXTRA_AUTHORIZE_PARAMS = (
    "response_mode",
    "nonce",
    "prompt",
    "login_hint",
    "user_scope",
)
```
Then I'm able to retrieve the token! 

I'm happy to help but I would need some guidance on how to fix that. I see that they are some "compliance_hooks" already for some piece of the code, but I'm not sure if there is on hook for that? if not, would that make sense to add some for that? or could we simply add that `user_scope` to these list?

Here are the URLs I'm using (based on loginpass provider):
```
class Slack(object):
    NAME = "slack"
    OAUTH_CONFIG = {
        "api_base_url": "https://slack.com/api/",
        "access_token_url": "https://slack.com/api/oauth.v2.access",
        "authorize_url": "https://slack.com/oauth/v2/authorize",
        "client_kwargs": {
            "token_endpoint_auth_method": "client_secret_post",
            "user_scope": "identity.basic identity.avatar identity.email",
        },
        "userinfo_endpoint": "users.identity",
        "compliance_fix": slack_compliance_fix,
        "userinfo_compliance_fix": sync_to_async(normalize_userinfo),
    }
```

**Comment by lepture** [comment]
@boertel You don't need to patch this `EXTRA_AUTHORIZE_PARAMS`. You can always pass `user_scope` in `create_authorization_url` method. If you are using Authlib framework related client, or loginpass, you can set:

```
authorize_params: { "user_scope": "identity.basic identity.avatar identity.email" }
```

**Comment by lepture** [comment]
TODO: add documentation for `authorize_params`.

**Comment by boertel** [comment]
sorry for the delay, I just got time to get back on that project. But thank you, it works now. I'll close that issue then
