### ISSUE TITLE
Redirect_uri validation for clients with multiple redirect URIs registered

### ISSUE THREAD

**Issue by seweissman** [lepture/authlib#302]
According to RFC 6749 if the client has multiple redirect_uris registered then it must pass in a redirect_uri argument:

```
 3.1.2.3.  Dynamic Configuration

   If multiple redirection URIs have been registered, if only part of
   the redirection URI has been registered, or if no redirection URI has
   been registered, the client MUST include a redirection URI with the
   authorization request using the "redirect_uri" request parameter.

```
However in the `validate_authorization_redirect_uri` there is never a check for this case. This can't be handled in the client because the client `check_redirect_uri` function is only called if redirect_uri is defined:

https://github.com/lepture/authlib/blob/36d5b3667520baada9135655c4e1377f4aec1177/authlib/oauth2/rfc6749/grants/base.py#L122-L135

Is there another place where this check could/should happen?

**Comment by lepture** [comment]
“client.get_default_redirect_uri()” if client has multiple redirect uris, this function can return None.
