### ISSUE TITLE
ResourceProtector decorator doesn't work with class-based Django views

### ISSUE THREAD

**Issue by thatguysimon** [lepture/authlib#305]
**Describe the bug**

When using the ResourceProtector decorator (as documented [here](https://docs.authlib.org/en/latest/django/2/resource-server.html)) on a Django REST Framework **class-based view**'s method:

```python
class MyView(APIView):
    @require_oauth("order")
    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)
```

I get the following error:

> 'MyView' object has no attribute 'get_raw_uri'

This is because in this case, the first parameter in the [decorator's `decorated` function](https://github.com/lepture/authlib/blob/ffeeaa9fd7b5bc4ea7cae9fcf0c2ad9d7f5cf22a/authlib/integrations/django_oauth2/resource_protector.py#L36), will be the **view object**, rather than the request.

Adding a `view` parameter as the first parameter in the function fixes this.

```python
 def __call__(self, scopes=None, optional=False):
     def wrapper(f):
         @functools.wraps(f)
         def decorated(view, request, *args, **kwargs):       # <= Change here
             try:
                 token = self.acquire_token(request, scopes)
                 request.oauth_token = token
```

**Error Stacks**

```
File "/.venv/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/.venv/lib/python3.6/site-packages/authlib/integrations/django_oauth2/resource_protector.py", line 39, in decorated
    token = self.acquire_token(request, scopes)
  File "/.venv/lib/python3.6/site-packages/authlib/integrations/django_oauth2/resource_protector.py", line 25, in acquire_token
    url = request.get_raw_uri()
AttributeError: 'MyView' object has no attribute 'get_raw_uri'
```

**To Reproduce**

See code example in the bug description above.

**Expected behavior**

The decorator to work the same way as it does for function-based views.

**Environment:**

 - OS: OSX
 - Python Version: 3.6.9
 - Authlib Version: 1.0.0.dev0

**Additional context**

I'm available to create a PR to fix this if you tell me the approach you want to take here.

**Comment by thatguysimon** [comment]
I ended up implementing this as a DRF [custom permission class](https://www.django-rest-framework.org/api-guide/permissions/#custom-permissions) so instead of a decorator, I inherited from `ResourceProtector` and created a regular function version of `__call__` which just returns a boolean and called it from the permission class.

I feel like this is a more "DRF-way" of doing this.

**Comment by Tamupiwa** [comment]
Thanks! Just encountered this very issue. Are you able to share the custom permission class you wrote to solve this?

**Comment by thatguysimon** [comment]
@Tamupiwa I actually ended up writing a custom DRF Authentication class for authentication validation, and a custom permission class for validating access to a specific endpoint/resource.

(Please note this was based on authlib from 2 years ago.. I don't know what changes were made since then)

I can't share the whole thing but basically it was something like this:

A custom ResourceProtector with a `authenticate_token` method to be used instead of the decorator:
```python
class DRFResourceProtector(ResourceProtector):
    def authenticate_token(self, request):
        validator, token_string = self.parse_request_authorization(request)
        try:
            token = validator.authenticate_token(token_string)
        except JoseError:
            raise InvalidTokenError(realm=validator.realm)
        return token
```


DRF authentication and permission classes that use the resource protector:
```python
class CustomAuthentication(authentication.BaseAuthentication):
    def authenticate(self, request):
        resource_protector = DRFResourceProtector()
        token_validator = ... # for example JWTBearerTokenValidator or a custom implementation
        resource_protector.register_token_validator(token_validator)

        try:
            token = resource_protector.authenticate_token(request)
        except (InvalidTokenError, OAuth2Error, JoseError) as error:
            request.error = error
            raise exceptions.AuthenticationFailed()

        ...

class CustomPermission(permissions.BasePermission):
    def has_permission(self, request, view):
        token_validator = ...

        try:
            token_validator.validate_token(...)
        except InsufficientScopeError:
            return False

        return True
```

Hope this helps.
