### ISSUE TITLE
Bearer token validator in SQLAlchemy integration does not check if token is revoked or expired 

### ISSUE THREAD

**Issue by m-aciek** [lepture/authlib#318]
**Describe the bug**

`create_bearer_token_validator` in `sqla_oauth2.functions` module returns a validator that doesn't check if a token is revoked or expired.

**To Reproduce**

A minimal example to reproduce the behavior:
* run Authlib's Example of OpenID Connect 1.0 Provider,
* add example client,
* authenticate using the client credentials,
* gain access token,
* use gained access token the next day.

**Expected behavior**

Access token expires and doesn't let through.

**Environment:**

 - Authlib Version: 0.13

**Additional context**

This part of the implementation seems to be too simple:

```
def create_bearer_token_validator(session, token_model):
    """Create an bearer token validator class with SQLAlchemy session
    and token model.

    :param session: SQLAlchemy session
    :param token_model: Token model class
    """
    from authlib.oauth2.rfc6750 import BearerTokenValidator

    class _BearerTokenValidator(BearerTokenValidator):
        def authenticate_token(self, token_string):
            q = session.query(token_model)
            return q.filter_by(access_token=token_string).first()

        def request_invalid(self, request):
            return False

        def token_revoked(self, token):
            return token.revoked

    return _BearerTokenValidator
```

**Comment by lepture** [comment]
@m-aciek I'm going to remove SQLAlchemy integrations entirely. In this case, I won't fix the problem. People can define the database by themselves.
