### ISSUE TITLE
Align documentation with samples

### ISSUE THREAD

**Issue by Lawouach** [lepture/authlib#32]
Hey,

First of, thank you for this package! It's really useful.

I just wanted to report that the documentation is somtimes a bit lacking in places. I have been trying to use the Flask server support along with the GitHub integration and I keep getting a problem with the code being expired from GH.

I thought I'd look at the playground example but realised that it was quite different from the docs. There are aspects (like caching) that aren't setup as per the docs and it's unclear what needs to actually be done. 

Is the current doc up to date and authoritative or should I derive from the playground?

Thanks,

**Comment by Lawouach** [comment]
Okay so apparently, builtin cache is gone which makes the doc even less clear I'm afraid.

https://github.com/lepture/authlib/issues/23

I really wonder how to get a simplye GH client working with Flask :p

**Comment by Lawouach** [comment]
Right, so I should have probably pay attention to the version I was running. It was 0.4. After updating, and passing a Flask-Cache instance, I was able to get it to work!

For the record, I am using now:

```python
from flask.ext.cache import Cache

cache = Cache(app, config={'CACHE_TYPE': 'simple'})
oauth = OAuth(
        app, cache=cache, fetch_token=fetch_token_info,
        update_token=update_token)
```

I'll let you decide if this the doc is clear enough on this subject :)

**Comment by Lawouach** [comment]
I might be wrong but it seems that the update_token is not used anywhere, is it?

Also, fetch_token never seems to be called either. 

What are they used for?

**Comment by lepture** [comment]
I've updated the documentation so that you can understand what are `fetch_token` and `update_token`.

https://docs.authlib.org/en/latest/client/frameworks.html

BTW, don't use `flask.ext.*`, use `flask_*` instead.

**Comment by Lawouach** [comment]
Thanks. I think that helped!
