### ISSUE TITLE
ClientMixin's get_allowed_scope not used in authorization/consent step

### ISSUE THREAD

**Issue by ThiefMaster** [lepture/authlib#320]
The docstring currently states "A method to return a list of requested scopes which are supported by this client".

But when testing it by trying to authorize a scope that is not accepted by this function, I noticed this behavior:

- it never gets called while displaying the consent page
- it also doesn't get called when giving consent
- it only gets called when exchanging the code for a token, where the invalid scopes are *silently* discarded

I was able to ge  a much more logical behavior by overriding `validate_requested_scope` in my `AuthorizationCodeGrant` subclass like this:

```python
    def validate_requested_scope(self):
        """Validate if requested scope is supported by the Client and Authorization Server."""
        scope = self.request.scope
        state = self.request.state
        if scope:
            allowed = set(scope_to_list(self.request.client.get_allowed_scope(scope)))
            requested = set(scope_to_list(scope))
            if not (requested <= allowed):
                raise InvalidScopeError(state=state)
        return self.server.validate_requested_scope(scope, state)
```

But while this is easily doable and not too awful since I only have one grant type in my application, this feels wrong - shouldn't this kind of validation happen out of the box? As a developer of an app, I want to know quickly that I'm sending garbage and requesting a scope that doesn't exist (or which my app is not allowed to request).

As usual I wouldn't mind sending a PR to fix this logic if you agree that this change makes sense. I would also get rid of the `return` in there since `validate_requested_scope` on the AuthorizationServer does not use return values but raises an exception if the requested scope is not valid, and the presence of `return` makes one assume that there is a (meaningful) return value..

**Comment by lepture** [comment]
If you add this logic in `.validate_requested_scope`, it would raise an error in consent view. However, I saw a lot of services (including GitHub) are doing it in another way. Instead of raising an error, they just ignores the unsupported scopes in the consent view.

You can call this method in your consent endpoint view function. I've updated the documentation and added this function in the docs.
