### ISSUE TITLE
OAuth and JWT

### ISSUE THREAD

**Issue by Priyansh2001here** [lepture/authlib#323]
I am working on django + react app and want to integrate OAuth 2.0 using JWT

I tried to follow docs and found docs for integrating Authlib with django app but there was no option for integrating JWT with OAuth

```
<script>
function signInCallback(authResult) {
  if (authResult['code']) {

    // Hide the sign-in button now that the user is authorized, for example:
    $('#signinButton').attr('style', 'display: none');

    // Send the code to the server
    $.ajax({
      type: 'POST',
      url: 'http://example.com/storeauthcode',
      // Always include an `X-Requested-With` header in every AJAX request,
      // to protect against CSRF attacks.
      headers: {
        'X-Requested-With': 'XMLHttpRequest'
      },
      contentType: 'application/octet-stream; charset=utf-8',
      success: function(result) {
        // Handle or verify the server response.
      },
      processData: false,
      data: authResult['code']
    });
  } else {
    // There was an error.
  }
}
</script>
```

This code sends auth_code to backend server, there should be a way to authorize users based on this auth code 

I tried to follow this entire [guide](https://developers.google.com/identity/sign-in/web/server-side-flow)

**Comment by lepture** [comment]
@Priyansh2001here Hi. We only accept bug report and feature request in GitHub issues. If you are looking for someone's help, please try StackOverflow.
