### ISSUE TITLE
RFC8628 Device Flow only checks device code expiration when user consent is pending

### ISSUE THREAD

**Issue by gtrs** [lepture/authlib#324]
In the RFC8628 Device Flow, the client fetches a so-called device code from the AS's device authorization endpoint. The client uses this device code to repeatedly query the token endpoint for an access token. The token endpoint will provide this access token after the user has given consent over a different channel / secondary device. Until the user has stated her choice to the AS, the AS will tell the client to wait and try again until the device code eventually expires.

In Authlib, this expiration check, however, is only performed in the case the user has not noticed the AS of her consent decision. This means that if the user has given consent, the device code is valid indefinitely (or at least until purged from the set of active device codes).

This is the relevant code section:
https://github.com/lepture/authlib/blob/95c211c5fe4f512eaedb01d3569e88c9805d3929/authlib/oauth2/rfc8628/device_code.py#L130-L141

Proposal: swap order of the expiration and consent check.

**Comment by lepture** [comment]
Thanks. I've updated the logic.
