### ISSUE TITLE
Support HTTPX Client.stream in subclass OAuth2Client

### ISSUE THREAD

**Issue by ulodciv** [lepture/authlib#326]
**Describe the bug**

OAuth2Client doesn't work when calling method stream of base class Client.

Client.request is overridden in OAuth2Client: this is how auth is handled by Authlib. The problem seems to be that this method is not called when calling Client.stream.

**Comment by lepture** [comment]
@ulodciv can you help me review https://github.com/lepture/authlib/pull/306

I think this PR fixed the problem.
