### ISSUE TITLE
`[client]` extra removed on purpose?

### ISSUE THREAD

**Issue by ThiefMaster** [lepture/authlib#327]
Versions before 1.0.0a1 had a `[client]` extra that explicitly pulled in `requests`. This no longer exists.

The [commit](https://github.com/lepture/authlib/commit/b9743ebce367b6e37b6528ea5aad47e2fd1f174a#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7) where it was removed doesn't sound particularly related to it, so I wonder if this was on purpose or not.

**Comment by lepture** [comment]
It is on purpose, because Authlib contains not only requests client.
