### ISSUE TITLE
Allow setting `oauth_body_hash`

### ISSUE THREAD

**Issue by libre-man** [lepture/authlib#329]
**Is your feature request related to a problem? Please describe.**

When using OAuth 1 for the [LTI 1.1 protocol](http://www.imsglobal.org/specs/ltiv1p1/implementation-guide) setting the `oauth_body_hash` parameter is required for some implementations. Currently `authlib.oauth1.rfc5849.client_auth.ClientAuth` doesn't set that parameter in the `get_oauth_params` method.

**Describe the solution you'd like**

Add a switch (or always do it if the content type is not `CONTENT_TYPE_FORM_URLENCODED`) to allow adding `oauth_body_hash`.

**Describe alternatives you've considered**

We currently subclass `ClientAuth` however this isn't a clean solution as the `body` value is not yet available in `get_oauth_params`, and thus it requires more overrides than wanted.

**Comment by lepture** [comment]
@libre-man added in master code.
