### ISSUE TITLE
Unable to import JWTBearerToken from authlib.oauth2.rfc7523

### ISSUE THREAD

**Issue by dcs3spp** [lepture/authlib#344]
Hi,

I am trying to use ```JWTBearerToken``` from ```authlib.oauth2.rfc7523```.  However, I have encountered import error when trying to import ```JWTBearerToken```:
 
*Create a virtual environment and install authlib*
```console
$ pyenv virtualenv authlib
$ pyenv activate authlib
$ python -m pip install --upgrade pip
$ pip install authlib
```

*Start authlib and try to import ```JWTBearerToken```
```python
>>> from authlib.oauth2.rfc7523 import JWTBearerToken
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'JWTBearerToken' from 'authlib.oauth2.rfc7523' (/Users/simon/.pyenv/versions/authlib/lib/python3.8/site-packages/authlib/oauth2/rfc7523/__init__.py)
>>> 
```

**Try and import via validator module**
```python
>>> from authlib.oauth2.rfc7523.validator import JWTBearerToken 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'authlib.oauth2.rfc7523.validator'
```

The source for the module is [here](https://github.com/lepture/authlib/blob/169c7dcfc47478c8d55553cc95fb0f5578162b77/authlib/oauth2/rfc7523/__init__.py).

What is the correct way to import JWTBearerToken or is this a bug with ```authlib``` library?

**Comment by lepture** [comment]
It's your environment problem.
