### ISSUE TITLE
Unable To Import authlib.oauth2.rfc7523.JWTBearerToken In A Fresh Virtual Environment on MacOS Catalina and Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by dcs3spp** [lepture/authlib#350]
Hi

I have tried upgrading to Python 3.9.5 on a macos Catalina and Ubuntu Linux environment via pyenv.

In both cases I have followed this procedure:
```console
$ pyenv virtualenv 3.9.5 authlib
$ pyenv activate authlib
$ python -m pip install --upgrade pip
$ pip install --no-cache authlib
```

In both cases :

```python
import authlib
print(authlib.__version__)
```

Prints 0.15.3.

In both cases I am unable to install ```JWTBearerToken``` from ```authlib.oauth2.rfc7523```:

```bash
>>> from authlib.oauth2.rfc7523 import JWTBearerToken
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'JWTBearerToken' from 'authlib.oauth2.rfc7523' >>> 
```

Would it be possible for someone to confirm that they are able to get this import working in a virtual environment on their macos or Linux platform?

**Comment by lepture** [comment]
There is no `JWTBearerToken` in that module, please check:

https://github.com/lepture/authlib/blob/v0.15.3/authlib/oauth2/rfc7523/__init__.py

`JWTBearerToken` was added in v1.0.0. Currently you can try to install:

```
pip install authlib==1.0.0a1
```
