### ISSUE TITLE
What is in the version 0.15.4

### ISSUE THREAD

**Issue by kawa-marcin** [lepture/authlib#353]
A new version of Authlib has been released on the `pypi` but it's nowhere to be found on GitHub tags nor the changelog. Did anything changed or was that version released due to some error?

https://pypi.org/project/Authlib/

Thanks!

**Comment by m-aciek** [comment]
Moreover it seems that 0.15.4 is missing recent changes on master, e.g. 49a8d8e53dccc73409a61fecd5a1c760fdf5cf74.

**Comment by lepture** [comment]
Release note and code will be available after two weeks. It is an early fix version for Authlib plus users.

**Comment by jeking3** [comment]
Any updates on this?

**Comment by jeking3** [comment]
Here are the code diffs between 0.15.3 and 0.15.4, which was published to pypi but code was not pushed here:
```
diff -r /home/jking/truth/conserv/ctcaas/.tox/py39/lib/python3.9/site-packages/authlib/consts.py /home/jking/.local/lib/python3.9/site-packages/authlib/consts.py
2c2
< version = '0.15.3'
---
> version = '0.15.4'
diff -r /home/jking/truth/conserv/ctcaas/.tox/py39/lib/python3.9/site-packages/authlib/jose/rfc7519/claims.py /home/jking/.local/lib/python3.9/site-packages/authlib/jose/rfc7519/claims.py
61,62c61
<         value = self.get(claim_name)
<         if not option or not value:
---
>         if not option:
64a64
>         value = self.get(claim_name)
```

I see no other packaging-related changes based on the pypi dist-info.

**Comment by jeking3** [comment]
@lepture will you be making the changes official any time soon?

**Comment by lepture** [comment]
There is a release note in GitHub releases now.
