### ISSUE TITLE
Authlib 0.15.x crashing with httpx 0.18.2

### ISSUE THREAD

**Issue by alessandroralc** [lepture/authlib#361]
After upgrading to HTTPX 0.18.2, the starlette oauth module (provided by Authlib) started to crash.

When i call the oauth authorize_redirect method, i get the following error: Invalid "auth" argument: <httpx._config.UnsetType object at 0x7fb5ac920310>"}

In HTTPX 0.18.1, everything works like a charm.

**Comment by rushilsrivastava** [comment]
I think the relevant fix for this has already been made in https://github.com/lepture/authlib/commit/40276708374fcc7c0ee6b1ce4955dbe7db82f5ba, just pending release.

**Comment by alessandroralc** [comment]
Thanks for the info @rushilsrivastava ... I'll wait the next release.
