### ISSUE TITLE
Backward compatibility and API stability

### ISSUE THREAD

**Issue by nomad-software** [lepture/authlib#364]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when updating to a new version of authlib because of needless refactoring and especially removal of methods on models. Moving code around and renaming causes serious breakage between versions. We have many services using this lib and it's a total nightmare to update their dependencies (which we do regularly for security purposes). Because we have no idea what's changed with each release, and how our services will break we have to examine every single line and then perform full regression tests on everything using this lib. It's a terrible development experience, using a library should help development.

**Describe the solution you'd like**

My proposed solution is two fold

1. A focus on backward compatibility when developing this library.
2. Create a detailed change log/migration guide (for API and DB schema) for every release to help users of this library to migrate to newer versions.

**Describe alternatives you've considered**

Writing it ourselves or forking.

**Additional context**

None.

**Comment by lepture** [comment]
@nomad-software are you upgrading to 1.0.0 alpha versions? 

Each breaking version change I will create a gist guide like:

https://gist.github.com/lepture/726e07a737b20f111d570d1d0437d5d4
https://gist.github.com/lepture/ecf8ccdbb2ef4b635799d5669308cb50

**Comment by nomad-software** [comment]
We've done a few upgrades to our services and each has had problems. At least one of our services is now running 1.0.0 alpha as I did that the other day and noticed its version number.

Those linked gists are very useful and would probably be better done as part of https://docs.authlib.org/

**Comment by lepture** [comment]
@nomad-software these links are on page https://docs.authlib.org/en/latest/changelog.html

e.g.

```
Breaking Changes: find how to solve the deprecate issues via https://git.io/JkY4f
```

For each release, I will keep it backward compatible for at lease >=2 versions, and there will be a deprecate message. I think your problem is upgrading from an early version to a very new version. But Authlib has no new releases for a long time now.

**Comment by lepture** [comment]
@nomad-software did you check the changelog?

**Comment by nomad-software** [comment]
Yeah, I had a look. It's very helpful, please continue this into the future. Thanks!
