### ISSUE TITLE
Flask client still relies on requests (missing dependecy)

### ISSUE THREAD

**Issue by sergioisidoro** [lepture/authlib#365]
**Describe the bug**

I was following this documentation: https://docs.authlib.org/en/latest/client/flask.html

In Installation doc section (https://docs.authlib.org/en/latest/basic/install.html) it says to use Authlib with Flask we just need to install Authlib and Flask.

However, when using `authlib.integrations.flask_client.OAuth` we still get a missing requests dependency. The docs rightfully say that requests is an optional dependency. But the documentation implies (at least to me) that Authlib is able to use `flask.request`, and that `requests` library is not needed if Flask is used.

I'm using `Flask == 2.0.1`

**Error Stacks**

```
webservice_1  |     from authlib.integrations.flask_client import OAuth
webservice_1  |   File "/usr/local/lib/python3.9/site-packages/authlib/integrations/flask_client/__init__.py", line 3, in <module>
webservice_1  |     from .oauth_registry import OAuth
webservice_1  |   File "/usr/local/lib/python3.9/site-packages/authlib/integrations/flask_client/oauth_registry.py", line 4, in <module>
webservice_1  |     from .integration import FlaskIntegration
webservice_1  |   File "/usr/local/lib/python3.9/site-packages/authlib/integrations/flask_client/integration.py", line 4, in <module>
webservice_1  |     from ..requests_client import OAuth1Session, OAuth2Session
webservice_1  |   File "/usr/local/lib/python3.9/site-packages/authlib/integrations/requests_client/__init__.py", line 1, in <module>
webservice_1  |     from .oauth1_session import OAuth1Session, OAuth1Auth
webservice_1  |   File "/usr/local/lib/python3.9/site-packages/authlib/integrations/requests_client/oauth1_session.py", line 2, in <module>
webservice_1  |     from requests import Session
webservice_1  | ModuleNotFoundError: No module named 'requests'
```

**To Reproduce**

- pip install Authlib Flask
- Follow https://docs.authlib.org/en/latest/client/flask.html

**Expected behavior**

- Authlib to use Flask requests interface, instead of requiring requests.

**Environment:**

 - OS: Docker (Apline)
 - Python Version: `3.9`
 - Authlib Version: `==0.15.4`

**Additional context**

- Could this be because some internal change to Flask 2.0, recently released? 
- Could a quick solution be just to update documentation to include requests also for a Flask installation?

**Comment by lepture** [comment]
You need to install `requests` yourself:

```
pip install requests
```
