### ISSUE TITLE
Python 3.9 package is at least 6 months behind despite having newest version tag.

### ISSUE THREAD

**Issue by sergioisidoro** [lepture/authlib#368]
From my pipfile:

```
        "authlib": {
            "hashes": [
                "sha256:37df3a2554bc6fe0da3cc6848c44fac2ae40634a7f8fc72543947f4330b26464",
                "sha256:d9fe5edb59801b16583faa86f88d798d99d952979b9616d5c735b9170b41ae2c"
            ],
            "index": "pypi",
            "version": "==0.15.4"
        },
``` 

Version `0.15.4` seems to be the latest version released 3 days ago: https://github.com/lepture/authlib/releases/tag/v0.15.4

However, when checking the code in: `lib/python3.9/site-packages/authlib/oauth2/rfc7662/__init__.py` I see this:
```
# -*- coding: utf-8 -*-
"""
    authlib.oauth2.rfc7662
    ~~~~~~~~~~~~~~~~~~~~~~

    This module represents a direct implementation of
    OAuth 2.0 Token Introspection.

    https://tools.ietf.org/html/rfc7662
"""

from .introspection import IntrospectionEndpoint
from .models import IntrospectionToken

__all__ = ['IntrospectionEndpoint', 'IntrospectionToken']
```

Which is missing at least this commit: https://github.com/lepture/authlib/blame/master/authlib/oauth2/rfc7662/__init__.py#L16, adding the `IntrospectTokenValidator` to the `rfc7662`

This was after some time getting this error:
```
webservice_1  |     from bottle.auth.openid_blueprint import open_id_blueprint
webservice_1  |   File "/code/bottle/auth/openid_blueprint.py", line 9, in <module>
webservice_1  |     from authlib.oauth2.rfc7662 import IntrospectTokenValidator
webservice_1  | ImportError: cannot import name 'IntrospectTokenValidator' from 'authlib.oauth2.rfc7662' (/usr/local/lib/python3.9/site-packages/authlib/oauth2/rfc7662/__init__.py)
webservice_1  | 
webservice_1 exited with code 2
``` 

To make sure I checked `/lib/python3.9/site-packages/authlib/consts.py` and it still outputs 0.15.4 (most recent one)
```
name = 'Authlib'
version = '0.15.4'
``` 

Is Python 3.9 supposed to be supported? Is the release commit somehow stuck in the past? Or am completely missing something here? I don't see any CI for making the release automatically, so I assume the releases are made manually?

**Comment by sergioisidoro** [comment]
Never-mind, `0.15.4` is still the latest version but does not contain `IntrospectTokenValidator`. I guess master is very much ahead of the stable.

**Comment by lepture** [comment]
@sergioisidoro please check https://github.com/lepture/authlib/tree/maintain-0.15

master code is for 1.0.0 releasing.
