### ISSUE TITLE
Interested in a meaningful contribution?

### ISSUE THREAD

**Issue by ashcherbakov** [lepture/authlib#370]
We've been working on a technology called [DIDComm](https://identity.foundation/didcomm-messaging/spec/). It makes heavy use of JWKs, JWEs, and JWSs. It's being done in FOSS in conjunction with the Decentralized Identity Foundation, Trust Over IP Foundation, and Linux Foundation. Eventually the spec that we're trying to implement is going to IETF.

After studying various python libs for JOSE, we have concluded that JOSE implementation from authlib is closest to what we'd like to start from. But we need some new features:
- ECDH-1PU support (see [ECDH-1PU draft](https://datatracker.ietf.org/doc/html/draft-madden-jose-ecdh-1pu-04))
- JSON serialization for JWS and JWE and multi-recipient support
- AEAD_XCHACHA20_POLY1305 (XC20P) support for content encryption (see [Chacha draft](https://datatracker.ietf.org/doc/html/draft-amringer-jose-chacha-02))

We could just pull some code out of your excellent library and do our own independent thing, but we're wondering if **you'd like a meaningful contribution of the features I listed above.** 

**We'd do the work; we're not trying to find someone else to do the coding for us.**

But before we start that contribution, we would like to know if it makes sense for you, and what are the chances that our **PRs with all the features listed above will be accepted** from the contributed features point of view. 

(Tagging @vimmerru and @dhh1128, who are interested in the answer).

**Comment by lepture** [comment]
@ashcherbakov thanks. You can put them in the `jose/drafts` folder.

**Comment by spivachuk** [comment]
Please review the following pull request adding ECDH-1PU (Draft 04) algorithm support to JWE:
https://github.com/lepture/authlib/pull/374

**Comment by spivachuk** [comment]
Please review the pull request adding XC20P encryption algorithm:
https://github.com/lepture/authlib/pull/375

**Comment by spivachuk** [comment]
Please review the pull request adding JSON serialization and multi-recipient support to JWE:
https://github.com/lepture/authlib/pull/380

**Comment by ashcherbakov** [comment]
@lepture Thank you for accepting all our contributions. Do you have any plans to create a new release that will contain all these changes?

**Comment by ashcherbakov** [comment]
@lepture 
We are planning to present the library we've been implementing ([DIDComm](https://github.com/sicpa-dlab/didcomm-python)) on a conference on Oct 12. That library depends on the authlib with the new JOSE features we contributed.
We would really appreciate a release of authlib with recent JOSE changes by Oct 12, so that we can have a release of our lib depending on authlib from pypi.

**Comment by lepture** [comment]
`1.0.0rc1` is released.
