### ISSUE TITLE
Allow overriding the signing algoritm used for JWT client assertion

### ISSUE THREAD

**Issue by janwijbrand** [lepture/authlib#389]
**Is your feature request related to a problem? Please describe.**

I'd like to have control over the signing algoritms used for the JWT client asserstion authentication variants. The current API doesn't allow to override the default `RS256`, even thought the lower-level signing helper functions are parameterized.

**Describe the solution you'd like**

When setting up an `PrivateKeyJWT()` instance to register as client auth method, I'd like to pass in the signing algoritm I'd like to use.

I will reference a PR against `maintain-0.15` branch for this feature request.

**Comment by lepture** [comment]
merged
