### ISSUE TITLE
authorize_access_token broken POST?

### ISSUE THREAD

**Issue by akam-it** [lepture/authlib#408]
Hello, I'm really not sure if it is a bug, but when I am trying to use authorize_access_token there is no params in POST body, as I understand they are sending in a new TCP packet (see a tcpdump picture)?

```
oauth = OAuth()
oauth.register(
    'zoom',
    client_id=os.environ['ZOOM_CLIENT_ID'],
    client_secret=os.environ['ZOOM_CLIENT_SECRET'],
    access_token_url='http://zoom.us/oauth/token',
    refresh_token_url='http://zoom.us/oauth/token',
    authorize_url='http://zoom.us/oauth/authorize',
    client_kwargs={'token_endpoint_auth_method': 'client_secret_post'},
)


def zoom_login(request):
    redirect_uri = request.build_absolute_uri('/zoom_authorize')
    return oauth.zoom.authorize_redirect(request, redirect_uri)


def zoom_authorize(request):
    print(request)
    token = oauth.zoom.authorize_access_token(request, body='aaaa=bbbbb')
    #resp = oauth.zoom.get('user', token=token)
    #resp.raise_for_status()
    #profile = resp.json()
    # do something with the token and profile
    #return profile
```

I've started tcpdump and can see this:
![image](https://user-images.githubusercontent.com/1487709/144701688-6ba4c20f-c26c-46ba-8d2c-436063d19c40.png)

I think it should be something like this?
```
POST /oauth/token HTTP/1.1
Host: zoom.us
User-Agent: Authlib/0.15.5 (+https://authlib.org/)
Accept-Encoding: gzip, deflate
Accept: application/json
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Content-Length: 216

aaa=bbb&client_id=xaaaaa&client_secret=aaaaaaaa&redirect_uri=ffsadfasd

```

**Comment by lepture** [comment]
Not sure what you are printing. It looks like the payload is encoded. Maybe it is because:

```
Accept-Encoding: gzip, deflate
```

**Comment by akam-it** [comment]
hm, I didn't set any additional headers, this code that I've posted is all logic, I just get it from the documentation. I have route /zoom_login -> def zoom_login and /zoom_authorize -> def zoom_authorize.
I go to zoom_login it redirects me to authorize_url='http://zoom.us/oauth/authorize' and after this it is redirects me to /zoom_authorize. and this POST query is generated by authorize_access_token(request)

I will google why Accept-Encoding is here and how to remove it
