### ISSUE TITLE
in v0.15.5, flask_client do not contain UserInfo in `authorize_access_token()` method

### ISSUE THREAD

**Issue by tan-i-ham** [lepture/authlib#409]
I used pipenv to install authlib, the lastest version is `v.0.15.5`
however, when I read the document, it said
```
when .authorize_access_token, the provider will include a id_token in the response. This id_token contains the UserInfo we need so that we don’t have to fetch userinfo endpoint again.
```
but when I look into the source code of authlib, I don't think it contains the UserInfo

https://github.com/lepture/authlib/blob/d8e428c9350c792fc3d25dbaaffa3bfefaabd8e3/authlib/integrations/flask_client/remote_app.py#L67

is the source code in the master branch will be tagged in the future?

**Comment by lepture** [comment]
@tan-i-ham Please check `v0.15` documentation. The master documentation is for `1.0.0` code.
