### ISSUE TITLE
attributes shall be resolveable on registered clients

### ISSUE THREAD

**Issue by jonas-weismueller-by** [lepture/authlib#410]
**Is your feature request related to a problem? Please describe.**

When I register a client like:

```
from authlib.integrations.starlette_client import OAuth,
oauth = OAuth()
oauth.register(
        name="example",
        client_id=client_id,
        client_secret=client_secret,
        server_metadata_url=well_known_url,
        client_kwargs={"scope": "openid profile email"},
        code_challenge_method="S256",
    )
```

and I access it via:
`oauth.example.authorize_redirect(request, redirect_uri)`

the attribute "authorize_redirect" is not resolvable via my editor (VSCode) and Pylance complains 
`"authorize_redirect" is not a known member of "None".`

**Describe the solution you'd like**

Registered clients shall be resolvable on the client object, so that I can easily browse references of authlib registered clients using my editor.
There is kind some magic happening in the background e.g. which OAuth client is finally chosen. It would be great to get this visible on each registered client.

**Comment by lepture** [comment]
You can use:

```
client = oauth.create_client('example')
client.authorize_redirect
```

Your editor should be able to inspect in this way.
