### ISSUE TITLE
Parse id_token returned from google-one-tap

### ISSUE THREAD

**Issue by saeedesmaili** [lepture/authlib#412]
I'm trying to use [google-one-tap][1] to authenticate users in the frontend. When a user performs the authentication and it's successful, it returns the following data:

```json
{
  "clientId": "--CLIENT_ID--",
  "credential": "eyJhbGciOi--SOMETHING--",
  "select_by": "user"
}
```
I can verify `data["credential"]` on Google side (using [this id_token endpoint][2]), and 
the output is user's information.

Is there a way to use Authlib and parse this id_token and verify it, and not use the Google's endpoint? I tried the [following code][3], but it also needs the access_token, but I only have the id_token:
``` python
token = await oauth.google.authorize_access_token(request)
user = await oauth.google.parse_id_token(request, token)
```

  [1]: https://github.com/BurakGur/google-one-tap
  [2]: https://oauth2.googleapis.com/tokeninfo?id_token=
  [3]: http://token%20=%20await%20oauth.google.authorize_access_token(request)%20%20%20%20%20user%20=%20await%20oauth.google.parse_id_token(request,%20token)

**Comment by lepture** [comment]
@saeedesmaili `id_token` is just JWT, you can use `authlib.jose` to validate it. Check our source code to learn how to use it:

https://github.com/lepture/authlib/blob/169c7dcfc47478c8d55553cc95fb0f5578162b77/authlib/integrations/base_client/sync_openid.py#L32-L77

**Comment by rushilsrivastava** [comment]
Out of curiosity, @saeedesmaili how did you end up implementing this?

**Comment by saeedesmaili** [comment]
@rushilsrivastava I used Google's endpoint for a while. I just got rid of google-one-tap later on, since neither authlib nor fastapo-users support it.
