### ISSUE TITLE
Introspection endpoint doesn't follow RFCs for invalid token

### ISSUE THREAD

**Issue by darkweaver87** [lepture/authlib#42]
Hello,

I'm not doing a PR as I don't know how do you want to correct this issue (serveral possibilities). Here: https://github.com/lepture/authlib/blob/bc971f244f39a6a2a420e8774073063823121af0/authlib/specs/rfc7662/introspection.py#L76
when the token doesn't exist it should return a 200 with active=false instead of an invalid request as the RFC mention it:

> If the introspection call is properly authorized but the token is not active, does not exist on this server, r the protected resource is not allowed to introspect this particular token, then the authorization server MUST return an introspection response with the "active" field set to "false"

On my side I just did return a special value in query_token and handled it in introspect_token.
Thanks.

Rémi

**Comment by lepture** [comment]
Thanks for your report. I've made some changes, can you verify if it works?

**Comment by darkweaver87** [comment]
Yes my unit tests are working without my "patch" so perfect to me :-)
Many thanks ! :1st_place_medal:
