### ISSUE TITLE
Handle PKCE pair generation

### ISSUE THREAD

**Issue by danlamanna** [lepture/authlib#420]
**Is your feature request related to a problem? Please describe.**

To perform an OAuth2 auth code + PKCE flow the client needs to create their own PKCE code verifier and pass it through, such as:
```py
import pkce

client = OAuth2Session(CLIENT_ID, code_challenge_method='S256')

pkce_code_verifier, pkce_code_challenge = pkce.generate_pkce_pair()

client.create_authorization_url(... code_verifier=pkce_code_verifier)

client.fetch_token(... code_verifier=pkce_code_verifier)
```

authlib already does the hashing and comparison, so generation seems like an appropriate addition.

**Describe the solution you'd like**

If passing a code challenge method, it would be nice if authlib generated and stored the code verifier, leaving the end user unaware of the lower level details of PKCE.

**Describe alternatives you've considered**

I've considered just wrapping the code to do the same, and will do just that if this feature isn't appropriate.

**Comment by lepture** [comment]
Authlib is already handling PKCE for you:

https://github.com/lepture/authlib/blob/master/authlib/oauth2/client.py#L143-L145


```py
code_verifier = generate_token(48)
client.create_authorization_url(... code_verifier=code_verifier)
client.fetch_token(... code_verifier=code_verifier)
```

I'll update this in OAuth 2 Session documentation.

**Comment by lepture** [comment]
Here are the docs:

- https://docs.authlib.org/en/latest/client/oauth2.html#add-pkce-for-authorization-code
- https://docs.authlib.org/en/latest/client/frameworks.html#oauth-2-0-code-challenge

**Comment by danlamanna** [comment]
Thanks for adding to docs! PKCE seems overlooked by so many libraries that it's nice to see Authlib supports it well.

> Authlib is already handling PKCE for you

What I was suggesting is that Authlib handle it without the user having to provide a token *at all*. The token has to be a certain length, it needs to be urlsafe, and it needs to be generated securely. It seems like several opportunities for an end user to make a mistake and generate an invalid or insecure token. I'm suggesting that PKCE be handled similarly to `state`: https://github.com/lepture/authlib/blob/c13679f540cb4c57d5131e92f33c9e498f437692/authlib/oauth2/client.py#L133-L134.

I'm suggesting adding something like:
```py
if self.code_challenge_method and code_verifier is None:
    code_verifier = generate_token(48)
```

Also out of curiosity, given the token should be between 43 and 128 characters, what was the reasoning for 48? (This is perhaps another reason it should be codified directly into Authlib!).

**Comment by lepture** [comment]
@danlamanna Because you need to use that `code_verifier` later in `fetch_token`. In our web framework integrations, this `code_verifier` will be generated automatically, because in web framework we have `cache` or `session` to remember those values.


The `48` length is just a number came out of my mind. Not a big thing.
