### ISSUE TITLE
Backport fix to support Django 4

### ISSUE THREAD

**Issue by V02460** [lepture/authlib#423]
Authlib 0.15.5 does not work with Django 4 due to the removal of `HttpRequest.get_raw_uri`. This is already fixed in master via https://github.com/lepture/authlib/commit/b3847d89dcd4db3a10c9b828de4698498a90d28c. Please backport the fix.

**To Reproduce**

With the latest release 0.15.5, run `tox -e py38-django` and see tests failing.

**Expected behavior**

All tests pass.

**Environment:**

 - OS: Fedora
 - Python Version: 3.8
 - Authlib Version: 0.15.5

**Comment by lepture** [comment]
v0.15.6 released.
