### ISSUE TITLE
Do I have to use `SessionMiddleware` with OAuth2 and Starlette?

### ISSUE THREAD

**Issue by haoyun** [lepture/authlib#425]
According to the documentation: [Enable Session for OAuth 1.0](https://docs.authlib.org/en/latest/client/starlette.html#enable-session-for-oauth-1-0), `SessionMiddleware` is required for OAuth 1.0. **Is it also required for OAuth 2.0?**

It seems also that in the code there is a `self.cache`  and when `session == None`, the `state` would be saved in `self.cache`.

https://github.com/lepture/authlib/blob/c13679f540cb4c57d5131e92f33c9e498f437692/authlib/integrations/starlette_client/integration.py#L36-L42

However, the line quoted below is trying to access `request.session`

https://github.com/lepture/authlib/blob/c13679f540cb4c57d5131e92f33c9e498f437692/authlib/integrations/starlette_client/apps.py#L13

Then `Starlette` will raise an exception
```
AssertionError: SessionMiddleware must be installed to access request.session
```

Should it check the availability of `request.session` first?

**Comment by lepture** [comment]
This is certainly a bug.

**Comment by lepture** [comment]
It is already fixed in https://github.com/lepture/authlib/commit/1089d5441c8e780a5165ca859b289fc8485ec5eb
