### ISSUE TITLE
`/.well-known/webfinger` endpoint

### ISSUE THREAD

**Issue by azmeuk** [lepture/authlib#426]
The [OpenID Connect discovery](https://openid.net/specs/openid-connect-discovery-1_0.html#IssuerDiscovery) specification second paragraph is about issue domain discovery based on the [RFC7033](https://datatracker.ietf.org/doc/html/rfc7033) webfinger.

Would it be relevant for authlib to provide helpers to implement this endpoint?

The main issue I can see is that this endpoint must be served at the top domain (i.e. `mydomain.tld` if the IDP is served at `auth.mydomain.tld`), but this can easily be solved with some webserver proxying configuration.

**Comment by lepture** [comment]
No. This spec should not be included in Authlib.
