### ISSUE TITLE
seeking authlib.integrations.quart_client

### ISSUE THREAD

**Issue by jonathonfletcher** [lepture/authlib#429]
**Is your feature request related to a problem? Please describe.**

I am migrating a project from [Flask](https://flask.palletsprojects.com/en/2.0.x/) to [Quart](https://pgjones.gitlab.io/quart/) - Quart being an asyncio reimplementation of the Flask api.

The migration is solely a python sync to python async migration. No functionality changes, just the adoption of async via migration from Flask to Quart.

In the Flask project, I am using:
`
from authlib.integrations.flask_client import OAuth
`
and it works well with my OAuth2 provider (thank you).

Quart implements the Flask api, and I am having (basic python sync / async) problems calling the sync flask_client.OAuth from the async Quart code.

```
oauth = OAuth(app)
oauth.register( .. provider .. )

@app.route("/sso/login", methods=["GET"])
async def sso_login():
    redirect_uri = url_for("sso_callback", _external=True, _scheme="https")

    # fails here due to calling into the sync flask api underneath OAuth
    return oauth.provider.authorize_redirect(redirect_uri)
```

**Describe the solution you'd like**

In my Quart project, I would love to use:
`
from authlib.integrations.quart_client import OAuth
`
and have this work with async Quart and Quart's async implementation of the Flask api.

**Describe alternatives you've considered**

I have looked at rolling my own OAuth client (using Authlib's OAuth2Session) and have not managed to get it working - lack of familiarity with Authlib and OAuth internals.

See #430

**Comment by lepture** [comment]
Not going to add as built-in integration. However, you can create your own package.
