### ISSUE TITLE
TokenValidator.scope_insufficient seems wrong

### ISSUE THREAD

**Issue by abompard** [lepture/authlib#432]
There's been changes in [TokenValidator.scope_insufficient()](https://github.com/lepture/authlib/blob/1089d5441c8e780a5165ca859b289fc8485ec5eb/authlib/oauth2/rfc6749/resource_protector.py#L33) to support nested required scopes, but I think it introduces a bug.

```
>>> from authlib.oauth2.rfc6749.resource_protector import TokenValidator
>>> TokenValidator.scope_insufficient(token_scopes=["read"], required_scopes=["read", "write"])
False
```
This seems wrong, since the token does not have all the required scopes. The reason is that now the function is looping over the required scopes, and as soon as it finds a matching scope it exists `False`. In this case it will not check the required `write` scope.

**Comment by lepture** [comment]
if `required_scopes` is a list, it will use OR logic. To use AND logic, you can use:

```
.scope_insufficient(token_scopes=["read"], required_scopes="read write")
```
