### ISSUE TITLE
Are you aware that another project shows up as dependency in many projects instead of your project?

### ISSUE THREAD

**Issue by pieterlukasse** [lepture/authlib#436]
**Describe the bug**

See this project: https://github.com/jessethegame/python-authlib

Notice it is unknown, virtually no forks or stars. 
Then go to https://github.com/jessethegame/python-authlib/network/dependents . Should these 21K projects be linking to your project instead? I think so!

**Comment by lepture** [comment]
This is GitHub's bug, not mine.

**Comment by pieterlukasse** [comment]
I know, but it affects your project, no? I just thought I'd let you know, so you can follow-up in whatever way you think is best, including closing this ticket!

**Comment by Guo-Zhang** [comment]
@pieterlukasse  Maybe you can report this problem for @lepture if you would like to help him.

**Comment by lepture** [comment]
Thanks. I've reported this issue to GitHub.

**Comment by lepture** [comment]
Added a `setup.py` file to fix this problem.
