### ISSUE TITLE
OpenIDCode documentation omits grant argument for get_jwt_config

### ISSUE THREAD

**Issue by jaap3** [lepture/authlib#439]
The documentation for [OpenIDCode](https://docs.authlib.org/en/latest/specs/oidc.html#authlib.oidc.core.grants.OpenIDCode) doesn't mention the `grant` argument for `get_jwt_config`.

The example implementation fails with a

`TypeError: get_jwt_config() takes 1 positional argument but 2 were given`

**Comment by lepture** [comment]
Thanks, fixed.

**Comment by lepture** [comment]
Thanks, fixed.
