### ISSUE TITLE
OAuth1 fetch_request_token fails with additional Kwargs

### ISSUE THREAD

**Issue by elaamrani** [lepture/authlib#490]
**Describe the bug**

I tried to initiate an Oauth1 session. The request_token method requires some parameters that I supply to the Oauth1 session.
Calling fetch_request_token with oauth_callback='oob' raises an error.

**Error Stacks**

```
{"message":"request() got an unexpected keyword argument 'oauth_callback'"}
```

**To Reproduce**

```
oauth.register(
    name="app",
    client_id="",
    client_secret="",
    request_token_url="https://api.example.com/oauth/request_token",
    request_token_params={"oauth_callback": "oob", "format": "json"},
    access_token_url="https://api.example.com/oauth/access_token",
    authorize_url="https://www.example.com/authorize",
    api_base_url="https://api.example.com",
)

oauth.app.authorize_redirect(request)
```

**Expected behavior**

```
Authorization: OAuth realm="",oauth_callback="oob",
oauth_signature="xxx", oauth_nonce="xxx",
oauth_signature_method="HMAC-SHA1",oauth_consumer_key="xxx",
oauth_timestamp="xxx"

```
**Environment:**

 - OS: python:3.9-alpine3.13
 - Python Version: 3.9
 - Authlib Version: 1.1.0

**Additional context**

I tried to debug the behavior and `self.fetch_request_token(), _fetch_token(url, **kwargs)` are called successfully. 
However, inside `_fetch_token`, it is the following call that raises the error
`resp = self.session.post(url, auth=self.auth, **kwargs)`

It also seems that oauth_callback="oob" is added as a parameter to post function which is not a valid argument. oauth_callback is not added to the authorization header as follows:

```
Authorization: OAuth realm="",oauth_callback="oob",
oauth_signature="xxx", oauth_nonce="xxx",
oauth_signature_method="HMAC-SHA1",oauth_consumer_key="xxx",
oauth_timestamp="xxx"
```

**Comment by lepture** [comment]
The parameter should be `redirect_uri='oob'`.

**Comment by lepture** [comment]
for `oob`, it means that you don't have a redirect_uri, in this case, you should use `OAuth1Session` directly.
