### ISSUE TITLE
Failed request error handling issue

### ISSUE THREAD

**Issue by JCapriotti** [lepture/authlib#492]
**Describe the bug**

There was a change in behavior from fixing #455. I don't know that it is a bug, but perhaps some clarification around request error handling is needed.

Previously if a request was not successful, `fetch_token` (and other methods) would raise an `HTTPError` from `requests`. 

Currently, there's two questionable error scenarios for a request that fails:
* If the request returns an error status and a plain text body, a `JSONDecodeError` will be raised. 
* If the request returns an error status with a JSON body, there is no error (but no valid token was fetched). 

**To Reproduce**

First example is the `JSONDecodeError` exception, second is a failure but with valid JSON. 

```python
from json import JSONDecodeError
import responses
from authlib.integrations.requests_client import OAuth2Session

client = OAuth2Session()
token_url = 'https://myserver.com/token'

with responses.RequestsMock() as rsps:
    rsps.add(responses.POST, token_url, status=500, body='Some Server Error')
    try:
        client.fetch_token(url=token_url)
    except JSONDecodeError as e:
        print(e)  # Expecting value: line 1 column 1 (char 0)

    rsps.add(responses.POST, token_url, status=500, json={'some': 'response'})
    print(client.fetch_token(url=token_url))  # {'some': 'response'}
```

**Expected behavior**

Since the `JSONDecodeError` in the first scenario prevents the error response from being logged, ideally the original response would somehow be returned. So something like:

* Return underlying request library exception (e.g. `HTTPError` in this case). At least in the case of `requests`, all response information is in that exception object, so this seems like a good option.
* Or, (maybe less preferred), handle all known exception cases (in this case, from `requests` and JSON decoding) and return one or more new exception types (likely from `AuthlibBaseError`?)

**Environment:**

 - OS: MacOS
 - Python Version: 3.9.13
 - Authlib Version: 1.1.0

**Comment by lepture** [comment]
@JCapriotti thanks for your report. It should be fixed in master code.
