### ISSUE TITLE
create a copy of DEFAULT_HEADERS for compliance hook

### ISSUE THREAD

**Issue by otryshko** [lepture/authlib#495]
**Is your feature request related to a problem? Please describe.**

In the refresh_token function of `oauthlib/oauth_client.py`, the headers are set to DEFAULT_HEADERS, and then `refresh_token_refresh` compliance hook is called. If compliance hook modifies the headers pointing to DEFAULT_HEADERS, it would taint global DEFAULT_HEADERS and all consequent calls would be using altered version of headers unintentionally
```
        if headers is None:
            headers = DEFAULT_HEADERS

        for hook in self.compliance_hook['refresh_token_request']:
            url, headers, body = hook(url, headers, body)
```
**Describe the solution you'd like**

headers should be set to a copy
```
headers = DEFAULT_HEADERS.copy()
```

**Describe alternatives you've considered**

Compliance hook implementation should be extra careful to not update headers/always create a copy to be returned

**Additional context**

**Comment by lepture** [comment]
Thanks for your feedback. I've fixed it in master code.
