### ISSUE TITLE
`nonce` is not checked in the validate() method of a jwt

### ISSUE THREAD

**Issue by marcrleonard** [lepture/authlib#497]
I'm curious why nonce is not not checked in the validate method. Is it because that is created as part of the token request? Should nonce then be checked manually?

**Comment by lepture** [comment]
`nonce` is not a defined claim in JSON Web Token. I guess you are parsing a token from OpenID Connect token, if so, you can pass `claims_cls=IDToken` in `jwt.decode` method.

The `IDToken` claim class is defined in `authlib.oidc.core.IDToken`.
