### ISSUE TITLE
Configure OAuthClient with OpenID Discovery configuration

### ISSUE THREAD

**Issue by lepture** [lepture/authlib#51]
https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

**Comment by lepture** [comment]
done by RFC8414

**Comment by ThiefMaster** [comment]
The RFC mentions `/.well-known/openid-configuration`, but authlib uses `/.well-known/oauth-authorization-server` - is this an older version of the RFC or a istake?

**Comment by lepture** [comment]
There are two RFCs.

1. `/.well-known/openid-configuration` is defined by OpenID Connect
2. `/.well-known/oauth-authorization-server` is defined by RFC8414

**Comment by leonidguadalupe** [comment]
Hi @lepture,  I need to expose this url btw for a 3rd party to get our urls.. but I'm not sure what to do.. Do I manually expose it? or is there a way in authlib to expose /.well-known/openid-configuration

**Comment by lepture** [comment]
@leonidguadalupe you can manually expose it.

**Comment by leonidguadalupe** [comment]
Thank you very much :)
