### ISSUE TITLE
Allow `authorize_redirect` to save user defined state data

### ISSUE THREAD

**Issue by n0061q** [lepture/authlib#521]
**Is your feature request related to a problem? Please describe.**
I am using Flask OAuth Client (https://docs.authlib.org/en/latest/client/flask.html#routes-for-authorization)
However there seem to be no proper way save user defined data to the state with `authorize_redirect` (and to extract in the `authorize` route  before calling `authorize_access_token`).
This is crutial for such use cases when client needs to redirect user to the original resourse after successfull authentication (e.g. see [this](https://auth0.com/docs/secure/attack-protection/state-parameters#redirect-users))

It can be worked aroud as described below but it is a bit hackish.

**Describe the solution you'd like**

It would be nice if `authorize_redirect` could accept user defined data to save in the state and some method that could get this custom data from the state later while handling the `/authorize` request.

**Describe alternatives you've considered**

Workaround (Flask)

```python
@app.route("/login")
def login():
    redirect_uri = url_for(".authorize", _external=True)
    # return oauth.provider.authorize_redirect(redirect_uri)

    # I want to save referer URL to the state data
    # https://github.com/lepture/authlib/blob/4bdc72415a69e2f7c8993dd8375258be4036af1e/authlib/integrations/flask_client/apps.py#L36-L45
    rv = oauth.provider.create_authorization_url(redirect_uri)
    rv.update(referer_url=request.headers.get("Referer"))
    oauth.provider.save_authorize_data(redirect_uri=redirect_uri, **rv)
    return redirect(rv["url"])


@app.route("/authorize")
def authorize():
    # here I retrieve state data from session to get the referer URL
    state_data = oauth.provider.framework.get_state_data(session, request.args.get("state"))
    # state is cleared by calling authorize_access_token
    token = oauth.provider.authorize_access_token()
    # ...
    return redirect(state_data.get("referer_url", url_for(".index")))
```
**Additional context**

**Comment by n0061q** [comment]
I submitted a PR with my take on the issue. I can add corresponding fixes to other integrations (django, starlette) once I have a green light.

**Comment by lepture** [comment]
@n0061q I think your workaround is ok, except that you can change the code to:

```py
    oauth.provider.save_authorize_data(referer_url=request.headers.get("Referer"))
    return oauth.provider.authorize_redirect(redirect_uri)
```

And what we need is a `get_authorize_data` method on the client.

**Comment by lepture** [comment]
@n0061q I think you may not understand what you want, from your description, the referrer url is not a part of the oauth flow, it is your application's logic requirements. In this case, you can just save the referrer url in your session:

```py
    next_url = request.headers.get("Referer")
    if next_url:
        session['next_url'] = next_url
    return oauth.provider.authorize_redirect(redirect_uri)
```

Then:

```py
next_url = session.get('next_url', url_for(".index"))
return redirect(next_url)
```
