### ISSUE TITLE
Please support urllib.request as a request client 

### ISSUE THREAD

**Issue by spacether** [lepture/authlib#540]
**Is your feature request related to a problem? Please describe.**

Some users may not want to use the requests library when making requests and may instead want to use std lib

**Describe the solution you'd like**

Please support [urllib.request](https://docs.python.org/3.6/library/urllib.request.html#module-urllib.request) as the a request client
This would allow this library to work without requiring requests when making sync requests

**Describe alternatives you've considered**

**Additional context**

**Comment by lepture** [comment]
The API is very different from requests and httpx, won't add it.
