### ISSUE TITLE
TypeError: update_token() got multiple values for argument 'name' in flask app

### ISSUE THREAD

**Issue by Frederick-S** [lepture/authlib#55]
I wrote a `update_token` method according to the [doc](https://docs.authlib.org/en/latest/client/frameworks.html#auto-refresh-token) in my flask app, but it shows `TypeError: update_token() got multiple values for argument 'name'`. Here is the code:

```py
def update_token(name, token):
    session['token'] = token
```

After debugging the source code I found that `self.token_updater` already contains the `name` in `keyword`, so I changed `update_token(name, token)` to `update_token(token, name)` and it works fine. Is the doc not updated or do I miss something? I am using authlib 0.7.

**Comment by lepture** [comment]
Questions should be asked on StackOverflow.

---

There are two `update_token`, the one with `name` is used in `OAuth`. The one without `name` is used on `register`. I didn't see your code, so I can't figure out what's wrong.
