### ISSUE TITLE
py.typed marker is missing

### ISSUE THREAD

**Issue by kshitij-enable** [lepture/authlib#562]
**Steps to reproduce**
```
from authlib.integrations.requests_client import OAuth2Session
from authlib.integrations.starlette_client import OAuth
```
run mypy type checker

**Stack trace**

Skipping analyzing "authlib.integrations.requests_client": module is installed, but missing library stubs or py.typed marker
Skipping analyzing "authlib.integrations.starlette_client": module is installed, but missing library stubs or py.typed marker

**Comment by lepture** [comment]
Authlib has no type hints yet. You're welcome to add type hints.
