### ISSUE TITLE
No way to generate tokens containing user data

### ISSUE THREAD

**Issue by ThiefMaster** [lepture/authlib#58]
In some use cases it's nice to be able to generate tokens that are not stored in a database but just contain signed data.

However, the `AuthorizationServer` has this code in `init_app`:

    self.generate_token = self.create_bearer_token_generator(app)

The function it calls only takes a string from the config which points to a function not accepting any arguments, so even if I specify a custom function to generate a token I cannot include any user data in it.

Assigning a custom function to `self.generate_token` is also problematic because it's assigned in `init_app`, which means I need to do it quite late - when I'm calling `init_app` of Flask extensions, I'm usually done setting everything up and do not expect having to assign a function only after that. Having to assign functions *after* calling `init_app` feels rather dirty. This is stuff people usually do at import time, not at config loading / app initialization time. Also, when using an app factory I might end up calling it more than once, so changing global state from there is even worse.

**Comment by lepture** [comment]
Yes, I agree with you. Actually, I had that in my mind from the beginning, but I don't know how I forgot such a thing when implementing it.

**Comment by lepture** [comment]
Feature implemented.

**Comment by ThiefMaster** [comment]
that was fast, thanks! gonna try it out.

btw, the change broke python 2.7 support since the inspect method you are using is python3-only

**Comment by ThiefMaster** [comment]
semi-related: it'd be nice  if the config value could be a callable instead of a string. when setting it from python code (and not a config file), being able to just pass the function directly is cleaner
