### ISSUE TITLE
Should `generate_token` not be using `secrets.SystemRandom` instead of `random.SystemRandom`?

### ISSUE THREAD

**Issue by amn** [lepture/authlib#588]
Looking at https://github.com/lepture/authlib/blob/a6e89f8e6cf6f6bebd63dcdc2665b7d22cf0fde3/authlib/common/security.py#L9, it's apparent `random.SystemRandom` is used with generation of values of security-sensitive nature. `random.SystemRandom` is a _pseudorandom_ number generator which must not be used for things like generation of authorization tokens, in the very least. Even [the documentation on the `random` module](https://docs.python.org/3/library/random.html) says as much:

> Warning: The pseudo-random generators of this module should not be used for security purposes. For security or cryptographic uses, see the [secrets](https://docs.python.org/3/library/secrets.html#module-secrets) module.

Instead and just like the Python documentation suggests, `generate_token` at least, should use `secrets.SystemRandom` which is a so-called cryptographically secure RNG and as such is fit for purpose of token generation.

Otherwise, the tokens (and nonces which are also generated by `generate_token`) are _forgeable_.

**Comment by bjmc** [comment]
The "pseudo-random generators" refers to the Mersenne Twister used by default if you call, e.g. `random.randint()`

In contrast, `random.SystemRandom()` is a wrapper around [`os.urandom()`](https://docs.python.org/3/library/os.html#os.urandom) that should be a cryptographically-secure source of entropy provided by the operating system.

>  os.urandom(size, /)

>    Return a bytestring of size random bytes suitable for cryptographic use.

The short answer to the title question is, "No": what this library is doing is secure. Maybe there's a case to be made that it would be more obvious to call `secrets.SystemRandom()` than `random.SystemRandom()` but the underlying implementation is identical

```python
>>> import secrets
>>> import random
>>> secrets.SystemRandom == random.SystemRandom
True
```

**Comment by amn** [comment]
I was indeed wrong about `random.SystemRandom` being PRNG, my bad.

I am well aware `secrets.SystemRandom` ends up importing `random.SystemRandom` but I think that's long-term dangerous assumption and also irrelevant here because a module like `random` or `secrets` communicates intent and context and that either one of these may, by nature of how and where Python development goes, change implementation and import something else or rely on a different mechanism altogether -- we're talking encapsulation and interfacing the module without assuming implementation. Will `authlib` then change the module it uses, when assumptions start breaking? Isn't it better to change the code _now_, for readability's sake in the very least? It is suspicious that despite the warning by documentation of `random` upstream, `authlib`, which from what I understand is used extensively for OIDC clients, relies on `random`?

**Comment by bjmc** [comment]
The security of `/dev/urandom` is almost certainly beyond the scope of this library.

As to the question of `secrets.SystemRandom` vs `random.SystemRandom` I think it's purely a matter of opinion. The `secrets` module has existed only since Python 3.6, so to me, as a question of readability `random.SystemRandom` is more familiar and obvious, but I don't feel that strongly about it, and others might disagree.

I think your concerns about possible future changes to the Python standard library are probably unfounded. The Python authors are surely well aware that `random.SystemRandom()` is used for cryptographic applications, and they would not change it to a less-secure implementation.

**Comment by lepture** [comment]
I'll close this issue for now, as `secrects.SystemRandom` is the same with `random.SystemRandom`. However, we may use `secrets.token_urlsafe` directly later in state generator or other things.
