### ISSUE TITLE
ClientMixin missing get_client_id

### ISSUE THREAD

**Issue by sanderevers** [lepture/authlib#60]
When implementing my own OIDC client based on `ClientMixin` I noticed that the contract not only requires the specified methods in `ClientMixin`, but also a property `client_id`.
It is accessed in `OpenIDMixin.generate_id_token`.

I would expect a method `get_client_id` in `ClientMixin` instead.

**Comment by lepture** [comment]
@sanderevers I was planning to remove those `get_xxx` methods since RFC7591 has defined certain names for a client. But, yes, I should make an abstract NotImplementedError on those properties.

What is the property name you are using?

**Comment by sanderevers** [comment]
I don't understand your question. Maybe I should make myself a little more clear. I run an `AuthorizationServer` for which I wrote a `query_client` function that returns instances of my own client class that implements the methods defined by `ClientMixin`.
The problem was that if I don't also include a property `client_id` in this class, the code setting the `aud` claim in OpenIDMixin will fail because it does `request.client.client_id`.

I think putting the client id in this `aud` claim is ok because the client can always verify this. But it occurs to me now that maybe you want to make this configurable too.

**Comment by lepture** [comment]
@sanderevers sorry, I didn't explain it well. How did you define you `client` class?

I'm going to force the `client` class to have `client_id` and `client_secret` properties since they are standard names in RFC7591. Are you using another name instead of `client_id`?

e.g.:

```py
class YourClient(...):
    client_id = 'xxx'  # not client_id?
```

**Comment by sanderevers** [comment]
No, I'm just using `client_id`, that's ok.
But initially I kept my clients in a dict with the `client_id` as key, and I didn't include it in the client class at all. So that's how I noticed.
