### ISSUE TITLE
Drop `starlette.config.Config` from the Starlette integration

### ISSUE THREAD

**Issue by Kludex** [lepture/authlib#612]
Hi, maintainer of Starlette here. 👋 

The `OAuth` class receives a `starlette.config.Config`, and forces users to instantiate it only for `authlib`. Note that the `config` module is a very small thing of Starlette.

Would it be possible for `authlib` to not use this `starlette` structure?

**Comment by Kludex** [comment]
I'll try to remove `Config` from Starlette. FYI

**Comment by lepture** [comment]
@Kludex The use of `starlette.config.Config` is only included in docs. I've just removed it from docs.
