### ISSUE TITLE
Have special character encoding be optional

### ISSUE THREAD

**Issue by 2373655r** [lepture/authlib#628]
**Problem**

I have an OAuth2 client secret with special characters (=,-,/). Special characters are getting encoded following the change in https://github.com/lepture/authlib/pull/594 meaning I cannot authenticate when on 1.3.0 . I also cannot change the client that is generating the secrets containing special characters.

**Suggested solution**

A parameter that lets you optionally disable encoding special characters in client_id and client_secret, either with the understanding that using a colon character will cause a failure, or have it so that only colon characters are encoded.

**Comment by lepture** [comment]
Fixed in 1.3.2
