### ISSUE TITLE
Request New Feature: JWS multiple signatures signed by different keys

### ISSUE THREAD

**Issue by snznedta** [lepture/authlib#64]
By using `def serialize_json(self, header, payload, key):` function, all signature is generated by one key. Could we support multiple keys? like 
`def add_signature(self, header, payload, key)`

**Comment by snznedta** [comment]
As documentation https://docs.authlib.org/en/latest/specs/rfc7515.html#authlib.specs.rfc7515.JWS.serialize_json
```
header = [
    {'protected': {'alg': 'HS256'}, 'header': {'kid': 'foo'}},
    {'protected': {'alg': 'RS256'}, 'header': {'kid': 'bar'}},
]
```
I mean when we have multiple headers as an array, the return value in signatures is all signed by the key I passed. I would like to have a function where I can pass multiple keys.

**Comment by lepture** [comment]
oh, I need to write a documentation for that. The `key` parameter can be a function:

```python
def key(header, payload):
    return get_the_right_key(header, payload)
```
