### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by bverhoeve** [lepture/authlib#664]
**Is your feature request related to a problem? Please describe.**

Pypi mentions support for Python 3.11. Is there a roadmap towards support for Python 3.12? Or is there a way to verify that the library would support Python 3.12.

**Describe the solution you'd like**

Support for Python 3.12

**Describe alternatives you've considered**

Staying with the latest supported version Python 3.11

**Comment by lepture** [comment]
1.3.2 should work

**Comment by fossdd** [comment]
> 1.3.2 should work

thats great! could you also publish 1.3.2 on pypi?

**Comment by lepture** [comment]
Released.
