### ISSUE TITLE
Release 1.3.2 - information missing

### ISSUE THREAD

**Issue by ThiefMaster** [lepture/authlib#674]
There's a 1.3.2 release on PyPI, but there's no changelog entry nor a GitHub release.
Since there is a matching [Git tag](https://github.com/lepture/authlib/releases/tag/v1.3.2) I guess it's a legitimate release, but *especially* for security-related libraries it'd be good to avoid such cases.

This might also be a good idea to fix your [GitHub action](https://github.com/lepture/authlib/actions/workflows/pypi.yml) that's supposed to push to PyPI... it's much nicer from a security point of view if packages are known to have been built and published from the public upstream source repo.

**Comment by lepture** [comment]
@ThiefMaster thanks for the report. I've fixed the action: https://github.com/lepture/authlib/commit/fdbb1cf90856b10d1ebe4fa12a9fb094da189f70

**Comment by ThiefMaster** [comment]
You may also want to look into using the [trusted publisher](https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file#trusted-publishing) option instead of the `password: ${{ secrets.PYPI_API_TOKEN }}`

**Comment by lepture** [comment]
@ThiefMaster oh, thank you.
