### ISSUE TITLE
Add type hints to authlib

### ISSUE THREAD

**Issue by fritz-trawa** [lepture/authlib#675]
**Is your feature request related to a problem? Please describe.**

There are no type hints for authlib, so running mypy on it gives the warning

```
Skipping analyzing "authlib.integrations.requests_client": module is installed, but missing library stubs or py.typed marker
```

**Describe the solution you'd like**

Type hints are included with the library

**Describe alternatives you've considered**

Ignoring the issue and just closing the ticket, e.g. #562

**Additional context**

Wouldn't it make sense to leave a ticket for this task open until someone is able to get to it? Mypy (or one of its alternatives) is becoming an established part of the Python development stack. I may try and do so myself as soon as I have a minute

**Comment by nint8835** [comment]
> Wouldn't it make sense to leave a ticket for this task open until someone is able to get to it?

I believe they have, I think #460 covers the same thing as this

**Comment by fritz-trawa** [comment]
Oh my bad, closing this then
