### ISSUE TITLE
Authenticate_none for Password Flow

### ISSUE THREAD

**Issue by ProstoMaxim** [lepture/authlib#71]
Consider Password Flow with authenticate_none method. Method's doc say "The client does not have a client secret.". Couldn't find any reference in RFC 6749 about this. Does client really has to have no client_secret or he chooses to not transfer it in token request? 
Eather way we should remove client.has_client_secret() check in authenticate_none method or delete nullable=False argument from OAuth2ClientMixin's client_secret column defenition.

**Comment by lepture** [comment]
removed `nullable=False`.

FYI, per RFC7591:

> "none": The client is a public client as defined in OAuth 2.0, Section 2.1, and does not have a client secret.

**Comment by lepture** [comment]
BTW, please don't combine "none" client authentication method with password grant, this is dangerous.
