### ISSUE TITLE
No option to disable sending creds in both auth header and body

### ISSUE THREAD

**Issue by thebenwaters** [lepture/authlib#76]
When using the Flask client and trying to authenticate with okta i'm getting the following error

```
authlib.common.errors.AuthlibBaseError: invalid_request: Cannot supply multiple client credentials. Use one of the following: credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body.
```
This is specificallyl an error from Okta not from authlib

*but* I'm been trying to debug and I think I've found the issue

If I set `auth=None` here

https://github.com/lepture/authlib/blob/master/authlib/client/oauth2_session.py#L189

The error turns into 

ּּ`Client authentication failed. Either the client or the client credentials are invalid.`

I tried patching it in the compliance_fix

```
def compliance_fix(session):
    def fix_protected_request(url, headers, data):
        headers['Authorization'] = 'Basic {}'.format(
            base64.b64encode('{}:{}'.format(CLIENT_ID, CLIENT_SECRET)).decode())
        print('HELLO', session, url, headers, data)
        return url, headers, data

    session.register_compliance_hook(
        'protected_request', fix_protected_request
    )
```

But it doesn't seem to reach.

Is it just not possible to do? Or am I missing something

Version 0.8

**Comment by lepture** [comment]
Please try with `token_endpoint_auth_method="client_secret_post" option. Don't add `compliance_fix`.

**Comment by thebenwaters** [comment]
@lepture It doesn't seem to be a documented kwarg for `authorize_redirect` or `authorize_access_token`. Where is that option?

**Comment by lepture** [comment]
Document added: https://docs.authlib.org/en/latest/flask/client.html#client-kwargs
