### ISSUE TITLE
Flask OAuth2 Authorization server lazy initialization broken in 0.8

### ISSUE THREAD

**Issue by noirbizarre** [lepture/authlib#79]
Flask OAuth2 authorization server is broken in 0.8 when using lazy init.

`authenticate_client`/`ClientAuthorization` is only instanciated once [here](https://github.com/lepture/authlib/blob/v0.8/authlib/specs/rfc6749/authorization_server.py#L20) but with lazy `init_app`, `query_client` is not yet provided and so equals to `None`. The `authenticate_client` value is never properly initialized when using a lazy `init_app`

**Comment by lepture** [comment]
It is fixed in the master branch. It will be released together with v0.9.

**Comment by lepture** [comment]
v0.9 is released
