### ISSUE TITLE
MissingAuthorizationError and UnsupportedTokenTypeError should probably result in status code 401

### ISSUE THREAD

**Issue by jcassee** [lepture/authlib#86]
My project is using a `BearerTokenValidator` as [described in the documentation](http://docs.authlib.org/en/latest/flask/oauth2.html#protect-resources). When I try to access the resource without an Authorization header or with a non-bearer token, the result is a status code 400 Bad Request. I think this should be a 401 Unauthorized.

The change would simply be adding `status_code = 401` to both classes.

**Comment by lepture** [comment]
It sounds reasonable. These two errors are not defined by RFCs.

How about sending a PR?

**Comment by jcassee** [comment]
Here it is: #88

**Comment by lepture** [comment]
Thanks. It is merged.

**Comment by jcassee** [comment]
Thanks, that was quick!
