### ISSUE TITLE
Feature request: preserve raw error data on exceptions

### ISSUE THREAD

**Issue by jcassee** [lepture/authlib#87]
Because authlib converts exceptions to `HTTPException` objects that have the error as a serialized string, it is difficult to use [error handlers](http://flask.pocoo.org/docs/1.0/errorhandling/#error-handlers) to change the error message format. It would be nice if the raw error data were preserved.

I think the idea was to have [standard JSON errors](https://tools.ietf.org/html/rfc6749#section-7.2) by default. Still, it might be better not to interfere in Flask's standard error handling mechanism if the application uses, say, [problem+json](https://tools.ietf.org/html/rfc7807), and let the typed exceptions bubble up.

**Comment by jcassee** [comment]
@lepture If you have a general idea of how you would like to see this implemented I would probably be able to do it.

**Comment by jcassee** [comment]
Sorry, you are right. I should have specified I was talking about the `ResourceProtector` verification mechanism. It calls `raise_oauth2_error` -> `raise_http_exception` directly.

**Comment by lepture** [comment]
Added a `raise_error_response` on `ResourceProtector`. Check the latest code.

**Comment by jcassee** [comment]
Great, thanks @lepture!
