### ISSUE TITLE
Allow both AND and OR logic for scopes in required_oauth

### ISSUE THREAD

**Issue by jcassee** [lepture/authlib#90]
Currently the scopes passed to the Flask [`require_oauth`](https://docs.authlib.org/en/latest/flask/oauth2.html#protect-resources) decorator are interpreted as a logical conjunction, i.e. the token must claim all scopes. However, it is sometimes useful to allow any of a number of scopes. This currently cannot be expressed.

Some ideas:
* Decorators can be stacked. If the scope argument of `require_oauth` would be changed to a logical disjunction, using the decorator multiple times could express a conjunction. (The token would be acquired multiple times, so a check for the presence of `current_token` might be useful.)
  ```
  @require_oauth(['read:books', 'admin:books'])
  def find_book(book_id):
      [...]

  @require_oauth('read:books')
  @require_oauth('read:authors')
  def find_author_by_book(book_id):
      [...]
  ```
* You could introduce a keyword parameter in `require_oauth` to indicate the "scope operator", `and` or `or`. The default could be `and` for backward compatibility.
  ```
  @require_oauth(['read:books', 'admin:books'], operator='or')
  def find_book(book_id):
      [...]

  @require_oauth(['read:books', 'read:authors'], operator='and')
  def find_author_by_book(book_id):
      [...]
  ```

Personally, I like the first option better, but maybe you have a better idea.

**Comment by lepture** [comment]
Thanks for your suggestions. It is added in v0.10.

**Comment by jcassee** [comment]
Thanks! I realized that the and/or design is less expressive than the other one (you cannot express "either read:books and write:books or admin:books") but you can question whether that is good API design.

**Comment by lepture** [comment]
The operator can be a function now. You can do whatever in the function.

**Comment by jcassee** [comment]
That's a great idea! Thanks, @lepture.
