### ISSUE TITLE
Missing scope on server side when using OAuthClient from Authlib

### ISSUE THREAD

**Issue by kyzima-spb** [lepture/authlib#96]
When I use any of the standard clients, according to the documentation, I pass the scope key in the client_kwargs argument.
```python
# Example config.py for Flask application
HAMSTER_API_BASE_URL = 'http://api:5000/'
HAMSTER_ACCESS_TOKEN_URL = 'http://api:5000/oauth/token'
HAMSTER_CLIENT_ID = 'CLIENT'
HAMSTER_CLIENT_SECRET = 'SECRET'
HAMSTER_CLIENT_KWARGS = {
    'grant_type': 'client_credentials',
    'scope': 'api'
}
```

The server side is also implemented using Authlib. When trying to get a token using the ClientCredentialsGrant grant, the scope on the server side is lost. As a result, the token is broken, the server gives it, but without scope.
```python
from authlib.flask.client import OAuth

def fetch_hamster_token():
    name = 'hamster'
    token = OAuth2Token.get(name=name)

    if token:
        delta = token.expires_at - datetime.now().timestamp()

        if delta > 60:
            return token.to_token()

    token = getattr(oauth, name).fetch_access_token(timeout=30)
    save_hamster_token(token)
    return token

oauth = OAuth()
oauth.register('hamster', fetch_token=fetch_hamster_token)
```

If you use curl, then this problem is not observed.

What am I doing wrong? And sorry for Google translator

**Comment by lepture** [comment]
I don't understand your question. You can provide a minimal project to reproduce your problem, describe with:

1. what are you doing?
2. what result are you expecting?
3. instead, what your code gives you?

**Comment by kyzima-spb** [comment]
Ok, I'll do it later, please do not close the question yet.

**Comment by lepture** [comment]
Fixed with https://github.com/lepture/authlib/commit/ade352bc9cb6ce2be332d964bc6c2725c65d6922

**Comment by lepture** [comment]
currently, you can use `fetch_access_token(scope='profile')`

**Comment by lepture** [comment]
BTW, your config:

```
HAMSTER_CLIENT_KWARGS = {
    'grant_type': 'client_credentials',
}
```

The config is invalid. It will not read `grant_type` from `CLIENT_KWARGS`.
